### ISSUE TITLE
Map items shouldn't decay after map is loaded

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#100]
Not only there is no point in it (why a item would be placed in the map to decay in some minutes), but it's not how Tibia ever worked. For exemple splashs can't be placed in map, because they decay. Container items don't decay regardless of anything. Some corpses don't have a no-decaying version, also limiting options.

**Comment by JakesFromBB** [comment]
Try to add actionID (can be the same for every) to each splash/item you don't want to decay. It worked for me on Avesta, so I guess it'll work here aswell.

**Comment by diegorodriguesvieira** [comment]
@JakesFromBB It can be a temporary solution, but imagine doing this at all splashs...

**Comment by babymannen** [comment]
I don't understand this issue. When it comes to splashes, there are two different setups with ids, one setup is supposed to decay, the other one is not. This is configured in items.xml. Or am I missing the point?

**Comment by peonso** [comment]
@JakesFromBB Adding action id is not working here in OTHire, it would still be a workaround nonetheless.
@babymannen splashes are only one exemple, I'm talking about items 2016-2021, there are no counterpart. You missing the point that there is no point on any item loaded by map to decay, and also that there are no counterpart for all decaying items.

**Comment by peonso** [comment]
done!
https://github.com/TwistedScorpio/OTHire/commit/18448e07e21f6613550c5d22758d7b19dd285119
