### ISSUE TITLE
Rune error

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#106]
You can shoot runes in objects you shouldn't be able to, like imoveable items. It shows the projectiles and runes loose charges but there are no area animation or spell effects.

**Comment by peonso** [comment]
@LuisPro it's bugged for you in your build?

**Comment by LuisPro** [comment]
@peonso tell me some example to test, sd on what item?

**Comment by peonso** [comment]
@diegorodriguesvieira Probably because of this issue.
@LuisPro seems we got a bug.

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/blob/322095b12dbbfe6644dff6a615f43d7dcd27e2ab/source/combat.cpp#L1259-L1261

This?

**Comment by diegorodriguesvieira** [comment]
Yes, this fix caused other bugs...hehe

**Comment by peonso** [comment]
Soo, we need to add a different check if the player is casting a rune spell or a monster casting an area spell.

**Comment by diegorodriguesvieira** [comment]
The problem is that we have no creature there to do the check... hehe

**Comment by LuisPro** [comment]
huh thats why... ;/

hmm...

**Comment by peonso** [comment]
You should be able to throw GFB at windows?

**Comment by LuisPro** [comment]
Yes.

**Comment by peonso** [comment]
https://otland.net/threads/tfs-1-2-tfs-0-4-othire-monster-cast-beam-and-wave-through-wall-critical-bug.239366/page-2 Why you changed the flag? From BLOCKPROJECTILE to BLOCKSOLID? That was the fuck up, changing to BLOCKPROJECTILE fix everything.

**Comment by LuisPro** [comment]
I dont remember why i use it.
