### ISSUE TITLE
door bugs?

### ISSUE THREAD

**Issue by Stoudemire** [TwistedScorpio/OTHire#108]
https://gyazo.com/76a2d55a60c700cd5c88bdcd1d043ae9

**Comment by peonso** [comment]
related to this

https://github.com/TwistedScorpio/OTHire/blob/master/data/actions/scripts/doors/door_open_horizontal.lua#L3-L6

Any suggestions?

**Comment by peonso** [comment]
If not possible to move south try north, else send "sorry not possible". Same for east/west.

**Comment by peonso** [comment]
Just tested on real tibia, you can use a door if you staying in the tile.
