### ISSUE TITLE
Virus on new othire exe?

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/OTHire#110]
My antivirus keeps giving me virus alerts with the new exe
![2016-11-04 13_01_07-twistedscorpio_othire_ opentibia server for tibia 7 72](https://cloud.githubusercontent.com/assets/7066891/20004891/31707592-a28f-11e6-9603-ae0a7e450d63.png)

**Comment by LaloHao** [comment]
Might be a false positive. but you can always compile it yourself

**Comment by peonso** [comment]
I'm not dealing with this, might be tons of stuff, I'm compiling it as always. I still suggest to compile it yourself as always.
