### ISSUE TITLE
Outfits

### ISSUE THREAD

**Issue by Stoudemire** [TwistedScorpio/OTHire#114]
where i can find the outfits 
cause i want add more outfits for players
maybe source?

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/blob/cd56d29f28b1c55b74ac4a194f94d29545c85d31/source/protocolgame.cpp#L956-L964

**Comment by Stoudemire** [comment]
I add new outfit to my client, how I can create outfit scroll?
ID outfit : 250

**Comment by Stoudemire** [comment]
@peonso

**Comment by peonso** [comment]
As it is now you cant. There will be a need to edit source code, no idea how it could be done.
