### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by killineoo** [TwistedScorpio/OTHire#116]
Please helpme ,i am trying to compile but it is giving this error

root@localhost:/home/server/source# make
make  all-am
make[1]: Entering directory `/home/server/source'
g++ -DHAVE_CONFIG_H -I.    -I/usr/include/libxml2  -I/usr/include/lua5.1    -D__USE_MYSQL__     -D__ENABLE_SERVER_DIAGNOSTIC__ -std=c++11 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGDATADIR=\"/usr/local/share/otserv\" -D_THREAD_SAFE -D__OLD_GUILD_SYSTEM__ -D_REENTRANT -Wall -g -O2 -MT databasemysql.o -MD -MP -MF .deps/databasemysql.Tpo -c -o databasemysql.o databasemysql.cpp
cc1plus: error: unrecognized command line option '-std=c++11'
make[1]: *** [databasemysql.o] Error 1
make[1]: Leaving directory `/home/server/source'
make: *** [all] Error 2

**Comment by diegorodriguesvieira** [comment]
@killineoo Try use ubuntu 14.04 or 16.04

**Comment by killineoo** [comment]
im instaled ubuntu 14.04 and 16.04 , and not compile bro :/
@diegorodriguesvieira @TwistedScorpio 

g++ -DHAVE_CONFIG_H -I.    -I/usr/include/libxml2  -I/usr/include/lua5.1  -D__USE_MYSQL__     -D__ENABLE_SERVER_DIAGNOSTIC__ -std=c++11 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGDATADIR=\"/usr/local/share/otserv\" -D_THREAD_SAFE -D__OLD_GUILD_SYSTEM__ -D_REENTRANT -Wall -g -O2 -MT databasemysql.o -MD -MP -MF .deps/databasemysql.Tpo -c -o databasemysql.o databasemysql.cpp
mv -f .deps/databasemysql.Tpo .deps/databasemysql.Po

**Comment by killineoo** [comment]
@diegorodriguesvieira  
You helped me a lot, I'm very grateful
