### ISSUE TITLE
error on start server

### ISSUE THREAD

**Issue by killineoo** [TwistedScorpio/OTHire#117]
help-me please database is correct configured :/ help please

killineo@localhost:/home/server$ :: OTServ Version 0.7.0
:: ============================================================================
::
:: Initializing the random numbers... [done]
:: Loading lua script config.lua... [done]
:: Using data directory ... [done]
:: Checking Connection to Database ...

Error: Database Connection Failed!
otserv: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.

[1]+  Aborted                 ./otserv

**Comment by diegorodriguesvieira** [comment]
### How to compile ###
#### Install libs: ###
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
sudo apt-get install autoconf
sudo apt-get install build-essential
sudo apt-get install pkg-config
sudo apt-get install libboost-all-dev
sudo apt-get install libgmp3-dev
sudo apt-get install libxml2-dev
sudo apt-get install liblua5.1-0-dev
sudo apt-get install libmysqlclient-dev
sudo apt-get install ccache
sudo apt-get install libssl-dev
```

Open source folder:
```
cd source/
```

Generate build files:
```
sudo sh ./autogen.sh
```

Configure build files:
```
./configure --enable-mysql --enable-server-diag
```

Finally compile:
```
sudo make
```

**Comment by killineoo** [comment]
When trying to compile for putty in vps with ubuntu 14.04 give this error bro :/ and other method mkdir ... dont open :/ darabase connection error :/


make[1]: Entering directory `/home/OTHire/source'
g++ -DHAVE_CONFIG_H -I.    -I/usr/include/libxml2  -I/usr/include/lua5.1    -D__USE_MYSQL__     -D__ENABLE_SERVER_DIAGNOSTIC__ -std=c++11 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGDATADIR=\"/usr/local/share/otserv\" -D_THREAD_SAFE -D__OLD_GUILD_SYSTEM__ -D_REENTRANT -Wall -g -O2 -MT databasemysql.o -MD -MP -MF .deps/databasemysql.Tpo -c -o databasemysql.o databasemysql.cpp
mv -f .deps/databasemysql.Tpo .deps/databasemysql.Po
g++ -DHAVE_CONFIG_H -I.    -I/usr/include/libxml2  -I/usr/include/lua5.1    -D__USE_MYSQL__     -D__ENABLE_SERVER_DIAGNOSTIC__ -std=c++11 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGDATADIR=\"/usr/local/share/otserv\" -D_THREAD_SAFE -D__OLD_GUILD_SYSTEM__ -D_REENTRANT -Wall -g -O2 -MT map.o -MD -MP -MF .deps/map.Tpo -c -o map.o map.cpp
^Cmake[1]: *** [map.o] Interrupt
make: *** [all] Interrupt

**Comment by diegorodriguesvieira** [comment]
Try with root user...

**Comment by killineoo** [comment]
This is the root user: /  
root@localhost:/home#

**Comment by diegorodriguesvieira** [comment]
Add me on skype, diego.ldn

**Comment by killineoo** [comment]
@diegorodriguesvieira
You helped me a lot, I'm very grateful
