### ISSUE TITLE
Pits of Inferno Maze

### ISSUE THREAD

**Issue by LaloHao** [TwistedScorpio/OTHire#118]
Theres some tiles not working yet since i don't know where they're supposed to go but at least you can get to the other side, i got the teleport locations from here https://www.youtube.com/watch?v=vAZSoOR41NY

movements.xml
```xml
	<moveevent event="StepIn" actionid="60054" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60053" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60052" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60051" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60050" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60049" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60048" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60042" script="The Pits of Inferno Quest/Maze.lua"/>
	<moveevent event="StepIn" actionid="60032" script="The Pits of Inferno Quest/Maze.lua"/>
```

maze.lua
```xml
local positions = {
   {60054, {x = 32827,y = 32314,z = 9}},
   {60053, {x = 32840,y = 32323,z = 9}},
   {60052, {x = 32855,y = 32296,z = 9}},
   {60051, {x = 32840,y = 32317,z = 9}},
   {60050, {x = 32854,y = 32323,z = 9}},
   {60049, {x = 32858,y = 32296,z = 9}},
   {60048, {x = 32856,y = 32289,z = 9}},
   {60042, {x = 32838,y = 32304,z = 9}},
   {60032, {x = 32841,y = 32275,z = 10}}}


function onStepIn(cid, item, pos)
   for _, tp in ipairs(positions) do
      if tp[1] == item.actionid then
         doTeleportThing(cid, tp[2])
      end
   end
   return true
end
```

**Comment by peonso** [comment]
It's supposed to not work, might be something still be there yet but will eventually be removed. Pits of Inferno wasn't present in 7.72.

**Comment by LaloHao** [comment]
I thought it was part of the hacked files from cipsoft just not implemented

**Comment by peonso** [comment]
The map in this repository is based in the converted files, but some minor parts were modified, since it already had houses and actions ids already configured, I had a better time fixing minor issues then getting a clean converted map with nothing configured.

The custom PoI was something that the map had that I not fully removed yet.

**Comment by peonso** [comment]
Just noticed it's OTHire repository, it's a datapack issue not related at all with the engine.

**Comment by LaloHao** [comment]
I misstook the repos, sorry
