### ISSUE TITLE
RSA KEY

### ISSUE THREAD

**Issue by Stoudemire** [TwistedScorpio/OTHire#119]
Hello, where I can change rsa key and **where I can find an rsa key generator?**

maybe **otserv.cpp** but what lines exactly

**Comment by diegorodriguesvieira** [comment]
https://github.com/TwistedScorpio/OTHire/blob/master/source/otserv.cpp#L490

**Comment by Stoudemire** [comment]
How I can change it?, where I can find a custom rsa key @diegorodriguesvieira

**Comment by peonso** [comment]
https://web.archive.org/web/20160325041404/http://vapus.net/generatersa
