### ISSUE TITLE
POOF bug - critical bug

### ISSUE THREAD

**Issue by LuisPro** [TwistedScorpio/OTHire#131]
How it works now:
for example 80ek, skills 80/80 full set + BOW and orc warrior attack you,
you will get 3 options what is wrong behavior:
- blood hit
- ![2017-03-08 16_43_23-tibia](https://cloud.githubusercontent.com/assets/6198792/23711135/465b1f7e-041f-11e7-89f2-cd402c61cc7a.png) - this hit
- POOF

How it should works:
same ek, same skills, same items, without def in eq u can get only 2 options:
- blood hit
- ![2017-03-08 16_43_23-tibia](https://cloud.githubusercontent.com/assets/6198792/23711135/465b1f7e-041f-11e7-89f2-cd402c61cc7a.png) - this hit

On real tibia you cant get POOF if u not wear shield, for me its **critical PvE bug**.
Poof happen also if i not wear any weapon and shield < its wrong behavior also!
screen of bug:
![2017-03-08 17_52_23-desktop 2017 03 08 - 17 51 37 03 dvr mp4 - bestplayer 2 106 beta](https://cloud.githubusercontent.com/assets/6198792/23714176/92c6e268-0428-11e7-9e8b-5416849ed07a.png)![2017-03-08 17_55_31-desktop 2017 03 08 - 17 51 37 03 dvr mp4 - bestplayer 2 106 beta](https://cloud.githubusercontent.com/assets/6198792/23714181/94e49770-0428-11e7-914c-a30349683f52.png)

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/blob/be0e711f34a56030bee9e96511d9562e0a2ce2cd/source/creature.cpp#L1077-L1086

**Comment by LuisPro** [comment]
@peonso can you please provide changes to fix it? i will test it in PvE and PvP.

**Comment by peonso** [comment]
https://medivia.online/forum/thread/8514/1

It's stated here that Fist is using if you holds nothing, or weapon skill with an weapon, meaning you could still Poof from them. I'm sure it's somehow right, as you can block with a weapon using it's defense value. I'm not sure it's right, since they also say you can't block ranged attacks, and from my tests you can.

**Comment by LuisPro** [comment]
Why you talk about fist? It has nothing to do with it. Like i say in first post. If u not wear anything with def (bow is no def, both hands empty is no def) u **cant** get Poof.

**Comment by LuisPro** [comment]
any feedback? ;s

**Comment by peonso** [comment]
Just went on live Tibia to test this, and I got a poof without shield nor weapon. When I equipped a bow, I couldn't get more poofs.

Why I think it happens like that. When you have a bow equipped, your defenseValue is 0, so regarding the formula you will never get a poof. Although, when you have no weapon nor a shield at all, your defenseValue is set as 7, so you can still block. As explained in Medivia thread, and it's consistent with behavior I just saw in live Tibia.

In OTHire we got a base defense value of 5 that is added regardless of conditions https://github.com/TwistedScorpio/OTHire/blob/b52e97938d28e0efdd7b2ddddd21725fa2c9b864/source/player.cpp#L539-L559 so shielding is boosted regardless. It should be changed to 7 and only be added if there is no value set, that can be a 0 (eg.: bow). As this:

	int32_t Player::getDefense() const
	{
		int32_t defenseSkill = 0;
		int32_t defenseValue = 7;
		int32_t extraDef = 0;
		float defenseFactor = getDefenseFactor();
		const Item* weapon = NULL;
		const Item* shield = NULL;
		getShieldAndWeapon(shield, weapon);

		if(weapon){
			defenseValue = weapon->getDefense();
			defenseSkill = getWeaponSkill(weapon);
			extraDef = weapon->getExtraDef();
		}

		if(shield && shield->getDefense() >= defenseValue){
			defenseValue = shield->getDefense() + extraDef;
			defenseSkill = getSkill(SKILL_SHIELD, SKILL_LEVEL);
		}

		if(defenseSkill == 0)
			return 0;

		if(vocation && vocation->getBaseDefense() != 1.0){
			defenseValue = int32_t(defenseValue * vocation->getBaseDefense());
		}

		return ((int32_t)std::ceil(((float)(defenseSkill * (defenseValue * 0.015)) + (defenseValue * 0.1)) * defenseFactor));
	}
