### ISSUE TITLE
Compile Problem - iomapotbm.obj

### ISSUE THREAD

**Issue by xGravediggerx** [TwistedScorpio/OTHire#132]
I have such an error
I did everything just like it was in the guide

1>------ Build started: Project: OTHire, Configuration: Release Win32 ------
1> otpch.cpp
1> actions.cpp
1> admin.cpp
1> allocator.cpp
1> ban.cpp
1> baseevents.cpp
1> beds.cpp
1> chat.cpp
1> combat.cpp
1> condition.cpp
1> configmanager.cpp
1> connection.cpp
1> container.cpp
1> creature.cpp
1> creatureevent.cpp
1> cylinder.cpp
1> database.cpp
1> databasemysql.cpp
1> databaseodbc.cpp
1> databasepgsql.cpp
1> databasesqlite.cpp
1> depot.cpp
1> exception.cpp
1> fileloader.cpp
1> game.cpp
1> globalevent.cpp
1> guild.cpp
1> house.cpp
1> ioaccount.cpp
1> iomapotbm.cpp
1> iomapserialize.cpp
1> ioplayer.cpp
1> item.cpp
1> items.cpp
1> logger.cpp
1> luascript.cpp
1> mailbox.cpp
1> map.cpp
1> md5.cpp
1> monster.cpp
1> monsters.cpp
1> movement.cpp
1> networkmessage.cpp
1> npc.cpp
1> otserv.cpp
1> outputmessage.cpp
1> party.cpp
1> player.cpp
1> position.cpp
1> protocol.cpp
1> protocolgame.cpp
1> protocollogin.cpp
1> raids.cpp
1> rsa.cpp
1> scheduler.cpp
1> scriptmanager.cpp
1> server.cpp
1> sha1.cpp
1> spawn.cpp
1> spells.cpp
1> status.cpp
1> talkaction.cpp
1> tasks.cpp
1> teleport.cpp
1> thing.cpp
1> tile.cpp
1> tools.cpp
1> trashholder.cpp
1> vocation.cpp
1> waitlist.cpp
1> weapons.cpp
1>iomapotbm.obj : error LNK2001: unresolved external symbol "public: __thiscall HouseTile::HouseTile(int,int,int,class House *)" (??0HouseTile@@QAE@HHHPAVHouse@@@Z)
1>D:\----OTHIRE----\OTHire\Release\OTHire.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by peonso** [comment]
Not really a bug.
