### ISSUE TITLE
Also crash

### ISSUE THREAD

**Issue by LuisPro** [TwistedScorpio/OTHire#134]
> -----05/03/2017 01:21:26 - Aaron Soulbringer (109.193.133.100Debug Assertion  Communication.cpp 1879
> Sun Mar 05 01:21:10 2017
> Windows Version: 6.1 build 7601 on 2 with Service Pack 1
> Graphic Engine: 2
> Last Packet Types: 109 030 160 160 160 160 160 160 160 160
> Last Packet: 038 000 030 109 080 000 068 000 007 001 080 000 069 000 007 109
> Player Position: [86,69,7]
> Player.cpp 383: exception occurred, reason:
> Network.cpp 885: exception occurred (ErrorCode = 0), reason:
> Control.cpp 1280: exception occurred (Type = 109), reason:
> Communication.cpp 1895: exception occurred, reason:
> Communication.cpp 1879: MoveCreature has been received for a coordinate where there is no creature anymore [bug0000017], reason:
>  sx: 2 sy: 5 sz: 0
>  Position: 1
>  zx: 2 zy: 6 zz: 0
>  dx: 0 dy: 1 dz: 0
>  abs_sx: 80 abs_sy: 68 abs_sz: 7
>  abs_zx: 80 abs_zy: 69 abs_zz: 7
>  Start Cylinder (1):  (409,0)
>  Start Cylinder (2):  (409,0)(-)(-)(-)(-)(-)(-)(-)(-)(-)
>  Destination Cylinder (1):  (409,0)
>  Destination Cylinder (2):  (409,0)(-)(-)(-)(-)(-)(-)(-)(-)(-)
> Comment: 

btw.
i was testing monsters behavior on rl files and i see how many things works wrong on othire
should i report these things?

**Comment by diegorodriguesvieira** [comment]
This is a debug on client?

**Comment by LuisPro** [comment]
I think yes someone got it. i take it from client_assertions.txt

**Comment by diegorodriguesvieira** [comment]
Do you remember what made this debug happen?

**Comment by LuisPro** [comment]
Nope sorry, it not happen to me, just to one of my players.

**Comment by peonso** [comment]
> i was testing monsters behavior on rl files and i see how many things works wrong on othire
should i report these things?

@LuisPro please report.
