### ISSUE TITLE
Monster Corpses on Item.otb

### ISSUE THREAD

**Issue by jpgmassuco** [TwistedScorpio/OTHire#138]
I have found one bug on items.otb, not critical, but need to be fixed.
First, how i have found this bug?
I was testing my script of skinning knife (like obsidian knife) on othire (latest version) and my script is when player use one item (one knife for example) on a dead monster it have a chance of add to the player one item, and the dead monster decay to other corpse.
---> example: 
dead minotaur (corpse 2830)when i use the knife it do:
`doTransformItem(itemEx.uid, itemEx.itemid + 1)`
And the dead corpse 2830 transform on 2831

Note that the corpse 2830, you can open the corpse and take the items there.
BUT, if the corpse decay to 2831 you can't open the monster.

It dont happens with minotaur, minotaur are OK, it happened with orcs and other monster corpses.
I have fixed some monsters, the problem are on items.otb, some corpses are not a container.

NOTE that it don't happen only with my script, it happened normally when monster decay to the next corpse stage.

FINISHING: the solution is fix all monster corpses that need to be opened and cant be opened on items.otb with itemeditor. I will do this, and I need some help to share this on github, I dont know how to do this.
If anyone have question with this problem, or if i wasnt clear, I will try to exlpain more.

**Comment by diegorodriguesvieira** [comment]
I'm not sure, but I think it's normal, some corpses open when they go to stage 2, others do not open...

**Comment by jpgmassuco** [comment]
hmm, maybe..
I will check it, if you are sure, it is not a bug, but if you are wrong, we can fix easily.
I have found other issue, i have posted on threas of version 0.0.3 of othire on otland, a issue about  npcs.

**Comment by peonso** [comment]
In 7.72 the items ids weren't put in order with those kind of scripts on mind, at least in otservers. You could solve your problem by designating a specific itemid for each corpse item to be transformed to by adding a table in your script.
