### ISSUE TITLE
NPCs

### ISSUE THREAD

**Issue by jpgmassuco** [TwistedScorpio/OTHire#139]
When you say bye for a NPC, the NPC change your lookdir to North, and instantly walk away normally, but on this interval, he looks to north, then continue.

Also when you say one thing to the npcs, like: Buy Rope
The npc are too slow to answer, he delay like 2 seconds to answer, he not answer instantly like rl tibia.

**Comment by jpgmassuco** [comment]
Fixed delay of NPC answer. I have changed on data/npc/scripts/lib/npcsystem/npchandler.lua:
> NPCHANDLER_TALKDELAY = TALKDELAY_ONTHINK
for:
> NPCHANDLER_TALKDELAY = TALKDELAY_NONE

And changed:
> talkDelayTime = 1,
for
>talkDelayTime = 0,

BUT the bug that NPC change lookdir to north everytime you say bye for him continues.

**Comment by tarantonio** [comment]
Can't reproduce the bug. 
Just downloaded distro and made a server, when you say bye to npc it doesn't look north:
![gif](https://user-images.githubusercontent.com/7066891/28211075-11020adc-689b-11e7-9a1a-1fdfa973d0cd.gif)

**Comment by jpgmassuco** [comment]
your npc instantly turns to south. lol. I cant make a gif, but my npc turn to north ever.

**Comment by peonso** [comment]
Mine look to south also, As #140 I think it might me related to 5c8886a.

**Comment by jpgmassuco** [comment]
@peonso do you thing that this can be fixed by setting this function to NOT TURN npc to any direction?
Then, when the player say bye, the npc will not turn to any direction, it will only say "Bye, etc etc" and start your walkinterval arround your spawn area.

**Comment by peonso** [comment]
@jpgmassuco revert the changes from 5c8886a, I probably gonna do that and test.

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/blob/7ad11fcaf13b6051765c568c7a7c51762e7ab94a/source/npc.cpp#L818
