### ISSUE TITLE
/s NPC command

### ISSUE THREAD

**Issue by jpgmassuco** [TwistedScorpio/OTHire#140]
When you use the command /s to place any NPC, you got debug, you can login again and dont get debugged again, but on USE /s NPC its instantly debug.
I was looking talkaction /s and it don't have one script, it have one function.

`<talkaction words="/s" access="3" filter="first word" `function="placeNpc"/>`

Where we can change this? Maybe is some wrong instantly effect that make the character debug.

**Comment by diegorodriguesvieira** [comment]
https://github.com/TwistedScorpio/OTHire/blob/1e7b6c83c07a70c412247d7176e08010f8de28e2/source/talkaction.cpp#L235

**Comment by diegorodriguesvieira** [comment]
https://github.com/TwistedScorpio/OTHire/blob/master/source/talkaction.cpp#L299

**Comment by Eldran** [comment]
I have the same problem when I summon any NPC using the command /s how can i fix it?

Thanks

@diegorodriguesvieira

Poderia me explicar?

Obrigado

**Comment by Anastaciaa** [comment]
I'll take a look on this when i have some thime

**Comment by Anastaciaa** [comment]
turnToInitialLookDirection is the problem i recommend to remove it

**Comment by peonso** [comment]
@Anastaciaa @diegorodriguesvieira 
Might be related to this? https://github.com/TwistedScorpio/OTHire/commit/5c8886a27dc164a38e58cb7b2606807fbf9bfe11

**Comment by Anastaciaa** [comment]
@peonso I'm pretty surethat it's because of that commit.

**Comment by tarantonio** [comment]
Why not an placenpc.lua?

Something like this but with othire functions
[https://github.com/tarantonio/theforgottenserver-7.4/blob/master/server/data/talkactions/scripts/place_npc.lua](url)

**Comment by Anastaciaa** [comment]
Are you using OTClient?

**Comment by tarantonio** [comment]
@Anastaciaa Yes I do

**Comment by peonso** [comment]
I didn't revert the commit because despite npc commands not working we got a feature that wasn't working before. #90 

>  Why not add a placenpc.lua?
> 
> Something like this but with othire functions
> https://github.com/tarantonio/theforgottenserver-7.4/blob/master/server/data/talkactions/scripts/place_npc.lua

We can't because there is no lua functions regarding it.

**Comment by JakesFromBB** [comment]
There is no debug if NPC have looktype of a monster. It only happens when it have normal outfits.
