### ISSUE TITLE
Wild Growth - Spell (exevo grav vita) and Rune don't working.

### ISSUE THREAD

**Issue by Eldran** [TwistedScorpio/OTHire#143]
The spell "exevo grav vita" and the "Wild Growth Rune" are not working ... in spell the player gets mana points used but there is no action player and the wild growth does not appear in front of him ... 

Using the rune player walk to the determined chosen squarm ignoring the function of distance using and nothing happens "you can not use on it"

**Comment by peonso** [comment]
You using latest files? I'm nearby sure it was already fixed.

**Comment by Eldran** [comment]
I downloaded the files in this month.
