### ISSUE TITLE
Area damage calculated for each target

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#145]
Random damage with runes, a gfb used to do the same damage to all targets, here the damage is calculated for each target.

If I GFB a monster for 150 damage, all the target should take 150 damage (players 75, half). Except for physical spells (since the values would be lowered by individual armor values/rolls).

Faloria fixed the issue in Avesta:

> Damage from area runes/spells (from both players and monsters) do now deal the same damage to all targets hit by the attack. This means that if you shoot a GFB and hit three different players, all of them will take the same damage. If a Dragon waves, the damage will be the same for all targets within the area. This does not apply to physical spells and/or runes such as Explosion Rune and Exori.

**Comment by babymannen** [comment]
In: void Combat::CombatFunc(Creature* caster, const Position& pos, ...
Under:
```
						}
					}
				}
			}

			combatTileEffects(list, caster, iter_tile, params);
		}
	}
```

add:

```
	if (data) {
		Combat2Var* var = (Combat2Var*)data;
		int damage = random_range(var->minChange, var->maxChange);
		var->minChange = damage;
		var->maxChange = damage;
	}
```

**Comment by peonso** [comment]
@babymannen 

It didn't work.

**Comment by babymannen** [comment]
https://pastebin.com/8hDyECsM credits: ferrus
