### ISSUE TITLE
Guildhall not managed in sources or scripts

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/OTHire#153]
We don't have a way to manage Guildhalls, it doesn't exist nothing related in libs>house.lua or in any source.

**Comment by tarantonio** [comment]
@diegorodriguesvieira you have checked this issue on [https://github.com/TwistedScorpio/OTHire/issues/123](url) as OK?

**Comment by diegorodriguesvieira** [comment]
@tarantonio Sorry, but lately I have no time to dedicate to OTHire

**Comment by peonso** [comment]
@tarantonio any documentation on how it should work?

**Comment by tarantonio** [comment]
Nothing out of tibia.com manual tip:

_Access to Guildhalls
Guildhalls are houses that are specifically designed to be used by guilds. Only a guild leader can rent one and invite guild members or other characters to the guildhall. This way, even free account players can get a home for their characters! Also guild leaders can make areas within the guildhall inaccessible to certain characters.
Further, all guildhalls are equipped with a depot locker. All people invited to the guildhall can access their depot chest, inbox and the Market from this depot locker.
Note: If the guild leader decides to place a bid for a guildhall, the system will check if there is a sufficient amount of money on the guild bank account. If the money on the guild bank account is not sufficient, the bid system will take the money from the guild leader's bank account._

**Comment by peonso** [comment]
https://web.archive.org/web/20060411074422/http://www.tibia.com:80/guide/?subtopic=manual&section=houses

https://web.archive.org/web/20060414203456/http://www.tibia.com:80/guide/?subtopic=manual&section=guilds

**Comment by Felipe1993** [comment]
@peonso merely It should work un tiempo way only guild leaders are able to get a guildhouse and guildhouse would be only sole between guild leaders if the guild is disbanded the owner of the guildhouse lose the guildhouse  and the whole items even those that are from others players are sent to the guild leader.
Regards

**Comment by peonso** [comment]
Could it be managed entirely by the webpage? If so there is nothing to deal with the engine. Can a person own 2 houses if set by the database through the website?

**Comment by Felipe1993** [comment]
@peonso Personally i have no problem with it ehm but if a guild leader owns a guildhouse ofcourse that he couldn't own a  "normal" house
in this case for guildhouse would be good to get it via website
pd: im not sure if i understood your question completely
let me know if it was what you were looking for (talking about my answer)
regards....

**Comment by Felipe1993** [comment]
So in others words it's simple, the Money Will be Charged throught bank and Guild houses are only obtainable by Guilds leaders. Also Guilds leaders are not allowed to get a house if he already own a guild house.  
Or get a Guild house if he has a house

**Comment by peonso** [comment]
This is a feature that could and should be handled through website and/or custom script.

**Comment by Felipe1993** [comment]
why this was closed? D: anyone have the script? to make possible that only leaders of a guild can own a guildhouse plus if someone (the leader) owns this house he'll not aviable to get a house meanwhile he owns the guildhouse

**Comment by Felipe1993** [comment]
maybe this will fix or handle this issue

https://otland.net/threads/help-i-want-guild-d00r.129959/#post-1258231
