### ISSUE TITLE
Can walk under 2 stacked parcels, 2 stacked chairs

### ISSUE THREAD

**Issue by jacklp90** [TwistedScorpio/OTHire#154]
Any solution for this issue?

**Comment by peonso** [comment]
It's not a issue since it's intended, it's the default behavior at 7.72. Accepting an commit to enable/disable it through config.lua though.

**Comment by Qwizer** [comment]
solution?

**Comment by Qwizer** [comment]
https://otland.net/threads/parcel-trap-8-6-0-4.243675/page-2

solution.

**Comment by Felipe1993** [comment]
@Qwizer do you have the codes written for othire? im looking for this

**Comment by Felipe1993** [comment]
bump i dont know how to edit codes to make it works with othire

**Comment by Anastaciaa** [comment]
invite me on discord Ruth1991#8423

**Comment by Felipe1993** [comment]
@Anastaciaa 

Hello i don't know how to add you into a chat at discord but here is my link:
https://discord.gg/jAMjzF
please addme, regards

**Comment by Felipe1993** [comment]
i've nt you a friendship request via discord @Anastaciaa
