### ISSUE TITLE
Can move creature corpses so far

### ISSUE THREAD

**Issue by jpgmassuco** [TwistedScorpio/OTHire#156]
As the title says, I can move creature corpses to all sqms on my screen.
In rl tibia, you can only move a corpse to 2 sqm arround you.
We can fix it? if yes, how?

**Comment by peonso** [comment]
Some corpses can be moved through the entire screen, it's normal behavior, they can also be put on your inventory. Some others aren't pickupable and can't be moved by more then 2 sqms.

We got here intended behavior, just logged in [Zanera](http://zanera.hopto.org) to confirm.
