### ISSUE TITLE
Auto-stack bug.

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#157]
If you inventory is full, but ex. you have a not stack of 3 meats, and try to throw more meats on that inventory you will get the _"You cannot put more objects in this container."_ message. If they are already in a container inside your inventory the message won't happen, with money items, it won't happen either. I'm nearby sure it's weight related, if the item weighs less then 1.00 oz the bug don't happen.

https://github.com/TwistedScorpio/OTHire/blob/1e7b6c83c07a70c412247d7176e08010f8de28e2/source/container.cpp#L390-L451

**Comment by JakesFromBB** [comment]
As far as I've checked this only happens on normal characters. On gods it works normally.

I'll check it out.

**Comment by JakesFromBB** [comment]
Overwrite this function with:
`ReturnValue Container::__queryMaxCount(int32_t index, const Thing* thing, uint32_t count,
	uint32_t& maxQueryCount, uint32_t flags) const
{
	const Item* item = thing->getItem();
	if(item == NULL){
		maxQueryCount = 0;
		return RET_NOTPOSSIBLE;
	}

	if( ((flags & FLAG_NOLIMIT) == FLAG_NOLIMIT) ){
		maxQueryCount = std::max((uint32_t)1, count);
		return RET_NOERROR;
	}

	int32_t freeSlots = std::max((int32_t)(capacity() - size()), (int32_t)0);

	if(item->isStackable()){
		uint32_t n = 0;
		
		if(index != INDEX_WHEREEVER){
			const Thing* destThing = __getThing(index);
			const Item* destItem = NULL;
			if(destThing)
				destItem = destThing->getItem();

			if(destItem && destItem->getID() == item->getID()){
				n = 100 - destItem->getItemCount();
			}
		}

		maxQueryCount = freeSlots * 100 + n;

		if(maxQueryCount < count){
			return RET_CONTAINERNOTENOUGHROOM;
		}
	}
	else{
		maxQueryCount = freeSlots;

		if(maxQueryCount == 0){
			return RET_CONTAINERNOTENOUGHROOM;
		}
	}

	return RET_NOERROR;
}`

It should help.
