### ISSUE TITLE
doSetGameState(GAME_STATE_SHUTDOWN) do not save houses

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#159]
as title says, would be good if it does

**Comment by okk3** [comment]
Hello Peonso,

on game.cpp line 181 instead of using:
```cpp
void Game::saveGameState()
{
	ScriptEnviroment::saveGameState();
}```

use following method: 
```cpp
void Game::saveGameState()
{
	if(gameState == GAME_STATE_NORMAL)
		setGameState(GAME_STATE_MAINTAIN);

	stateTime = 0;
	std::cout << "Saving server..." << std::endl;
	IOLoginData* ioLoginData = IOLoginData::getInstance();
	for(AutoList<Player>::listiterator it = Player::listPlayer.list.begin(); it != Player::listPlayer.list.end(); ++it)
	{
		it->second->loginPosition = it->second->getPosition();
		ioLoginData->savePlayer(it->second);
	}

	map->saveMap();
	ScriptEnvironment::saveGameState();
	stateTime = OTSYS_TIME() + STATE_TIME;

	if(gameState == GAME_STATE_MAINTAIN)
		setGameState(GAME_STATE_NORMAL);
}
```

As I think saveMap() does save houses.

Kindest Regards,
Okke

**Comment by peonso** [comment]
I won't address this as it's intended.

If someone want to shutdown the server saving it, make a talkaction script like this:

	function onSay(cid, words, param)
		doSetGameState(GAME_STATE_CLOSED)
		doSaveServer(true)
		doSetGameState(GAME_STATE_SHUTDOWN)
		return false
	end

**Comment by Felipe1993** [comment]
what's wrong with @okk3 code @peonso ?

**Comment by peonso** [comment]
@Felipe1993 no idea, the point is that it's intended to shutdown not save the server, you may want that, if you want to save before shutdown, you save then shut it down, no problem.

**Comment by Felipe1993** [comment]
Thank you @peonso
