### ISSUE TITLE
Stairhop delay set to 0 is bugged

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#162]
workaround is to set it to 10, it might be some issue with reading 0 as boolean, couldn't find a gross mistake at code.

**Comment by diegorodriguesvieira** [comment]
What is the bug?
https://github.com/TwistedScorpio/OTHire/blob/master/source/player.cpp#L1779

**Comment by peonso** [comment]
You can actually get exhausted while stairhopping.

**Comment by Anastaciaa** [comment]
I fixed it by removing whole code part.

**Comment by peonso** [comment]
Fix, line https://github.com/TwistedScorpio/OTHire/blob/master/source/player.cpp#L1779
should be 

     		if(g_config.getNumber(ConfigManager::STAIRHOP_EXHAUSTED) > 0){
