### ISSUE TITLE
Melee attack still not fixed correctly.

### ISSUE THREAD

**Issue by Anastaciaa** [TwistedScorpio/OTHire#167]
Whenever you change floor and you get instant melee hit by monster.

**Comment by peonso** [comment]
Search for `extraMeleeAttack` in the code and set to false. Do you have it documented if it really was not present in 7.72, or when the change was made?

**Comment by Anastaciaa** [comment]
I have it set to false. This kind of bug shouldnt happen on every tibia version.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6841661/30023846-7efb06ca-9171-11e7-9483-c94ca0718f0f.gif)
