### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by Qwizer** [TwistedScorpio/OTHire#169]
Look Guilds ingame not work, website my-acc and in the database created successfully

http://167.114.108.164/characters/GM+Sample

**Comment by peonso** [comment]
It's working in my server, might be something wrong with your database/website. Can you gimme a screenshot of that guild in your database?

**Comment by Qwizer** [comment]
![image](https://user-images.githubusercontent.com/9012031/30768351-7816d144-9fdc-11e7-9fce-da254bdacb97.png)
![image](https://user-images.githubusercontent.com/9012031/30768353-807e6ad6-9fdc-11e7-947d-ebd6a0f72467.png)
![image](https://user-images.githubusercontent.com/9012031/30768354-8aff3864-9fdc-11e7-9651-24fe01584366.png)

**Comment by peonso** [comment]
It's your AAC, it's working with guild_members table, should update players table at rank_id

**Comment by Qwizer** [comment]
Thank you, it worked.
