### ISSUE TITLE
Quotes shouldn't be required for spells like Find Person and Levitate

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#170]
Quotes shouldn't be required for spells like Find Person and Levitate, unless it is a bigger name, etc.

**Comment by peonso** [comment]
Kamino cloned this issue to peonso/oldguilcera

**Comment by okk3** [comment]
Hello Peonso,

I sent you the code via discord yesterday, PUSH IT PUSH IT!

Kindest Regards,
Okke

**Comment by Felipe1993** [comment]
could u release code here @okk3 pls?
regards

**Comment by okk3** [comment]
You're welcome!

**Comment by peonso** [comment]
@JasonRox18, they were never NEEDED, you can use them if you want. You should be able to _exani hur up_ instead of _exani hur "up_.

**Comment by Felipe1993** [comment]
OTHIRE rullzzzz
