### ISSUE TITLE
Locking a open door

### ISSUE THREAD

**Issue by Zolias** [TwistedScorpio/OTHire#173]
When trying to lock an open door you get the default cancel message. Locking and unlocking a closed door works just fine. The action script is fine so I'm guessing it's server source related.

**Comment by andersonfaaria** [comment]
it's not source related, check the script key.lua in actions/scripts:

`function onUse(cid, item, frompos, item2, topos)
	if (item2.actionid == 0 or
	   (isInArray(LOCKED_DOORS, item2.itemid) == false and
	    isInArray(LOCKED_DOORS, item2.itemid-1) == false and
		isInArray(LOCKED_DOORS, item2.itemid-2) == false)) then
		return false
	end
`
everytime you use return false on a actions script you will get 'Sorry not possible' as message. If you want to cancel the callback but consider the action as valid you should use return true and then send the correct message by function doPlayerSendCancel(cid, message).

The script is correct, it should only split the first if in 2 ifs:

```
if item2.actionid == 0 then return doPlayerSendCancel(cid, "This key doesn't fit this door.") end
if not (isInArray(LOCKED_DOORS, item2.itemid) or sInArray(LOCKED_DOORS, item2.itemid - 1) or sInArray(LOCKED_DOORS, item2.itemid - 2) then
   return doPlayerSendCancel(cid, "This key doesn't fit this door.")
end
```
Now you're able to set different messages as you wish.
If I'm not mistaken the script tried to deal with the follow situation:
- Using key in a opened door
- its not in the locked doors array (but it has actionid)
- checks door id -1
- checks door id -2

Anyway, the way it is written, should be able to close and lock the door. 
Unless the door id or the door id -1 or the door id -2 isn't in the table LOCKED_DOORS, but that's easy to fix.

**Comment by Zolias** [comment]
I used your suggestion but it did not solve the issue. It did allow me to add prints which shows where the issue is happening. We start with a door that is locked and has the action ID 1234. I use my key with the action ID 1234 on the door and it opens and transforms the door into + 2 which is the open, unlocked door. Now, for whatever reason the door loses its actionID now or it atleast cannot be read properly because if you use they 1234 key on the door now it will not close and lock. Instead, it will claim that "item2.actionid == 0" and jump into that if sentence. If you add a "print(item2.actionid) into that if section it clearly prints that the action ID of the open, unlocked door is 0, despite initially being 1234 when it was still a closed locked door. If you use the door and close (but not lock) it, it somehow "regains" its actionID and you can use the key on the door again, locking the door. Feel free to try the code yourself, I will leave the print sections as they greatly help figuring out where the issue lies but I'm either just too blind to find the mistake or something outside the script isn't quite right.


```
function onUse(cid, item, frompos, item2, topos)

	if item2.actionid == 0 then
		print(1)
		print(item2.actionid)
		return doPlayerSendCancel(cid, "The key does not match.") 
	end

	if not (isInArray(LOCKED_DOORS, item2.itemid) or isInArray(LOCKED_DOORS, item2.itemid - 1) or isInArray(LOCKED_DOORS, item2.itemid - 2)) then
		print(2)
		return doPlayerSendCancel(cid, "The key does not match.")
	end


	local canOpen = (item.actionid == 10000 or item.actionid == item2.actionid)
	if not(canOpen) then
		doPlayerSendCancel(cid, "The key does not match.")
		return true
	end

	-- Verify if you are opening or closing the door
	if(isInArray(LOCKED_DOORS, item2.itemid) ) then -- Opening
		print(item2.actionid)
		doTransformItem(item2.uid, item2.itemid+2)
		doPlayerSendCancel(cid, "The key matches and you unlock the door.")

	elseif(isInArray(LOCKED_DOORS, item2.itemid-2) ) then -- Closing and Locking NOT WORKING
		doTransformItem(item2.uid, item2.itemid-2)

	elseif(isInArray(LOCKED_DOORS, item2.itemid-1) ) then -- Locking an already closed door
		print(item2.actionid)
		doTransformItem(item2.uid, item2.itemid-1)
		doPlayerSendCancel(cid, "The key matches and you lock the door.")
	end

	doSetItemActionId(item2.uid, item.actionid)
	return true
end
```

**Comment by andersonfaaria** [comment]
It happens because when you transform the id, it does not carry the properties it had before. You have to save the action id in a variable and then transform and manually add the action id yourself. It happens even in the forgotten server original repository. What I tend to do in those cases is remove the transform function and use remove and create because when you use transform you can't get the uid of the transformed item.

**Comment by Zolias** [comment]
I tried around some more since I really dislike the thought of removing and adding the door again and finally found the issue: The ActionID is NOT removed when unlocking the door. The open, unlocked door still has the ActionID 1234. HOWEVER, the key you use ON the door does not actually "target" the door, but the floor below it (used print item2id). I assume that's because it prioritizes objects with the Bottom flag OR OTClient prioritizes it the wrong way. Unfortunately, I can not use a tibia client to check if it's OTC related.

Since I cannot tell if it's OTC or OTHire related we can probably close this issue. Thanks anyways andersonfaaria.

**Comment by andersonfaaria** [comment]
It's an otc issue, but I could swear it was because transform Item is wrongly removing the before properties.

**Comment by peonso** [comment]
@Zolias 
Just tested default client, it's work as intended, and I couldn't reproduce the issue.

@andersonfaaria 
`doSetItemActionId(item2.uid, item.actionid)` adds the correct actionId after the item is transformed.
