### ISSUE TITLE
Monster are slow dumb

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#174]
I fucked up https://github.com/TwistedScorpio/OTHire/commit/ce4c82cdafe455a4c565cb2502b20be1fad86c92
monsters standstill a bit when the player get out of melee range.

@babymannen has the fix.

**Comment by Zolias** [comment]
Would @babymannen mind commiting the fix? I have the issue in my built & would very much appreciate a fix for it.

**Comment by peonso** [comment]
@Zolias meanwhile you can revert the commit I pointed out.

**Comment by babymannen** [comment]
I don't know how to do the GitHub! But anyway:
Creature::getWalkDelay()
`int64_t stepDuration = getStepDuration() * lastStepCost; `
to
`int64_t stepDuration = getStepDuration(); `

Creature::getStepDuration()
`return duration; `
to
`return duration * lastStepCost; `

Creature::getEventStepTicks
`ret = getStepDuration() * lastStepCost; `
to
`ret = getStepDuration(); `
