### ISSUE TITLE
Creature Spawn Interval Issue

### ISSUE THREAD

**Issue by Zolias** [TwistedScorpio/OTHire#175]
I have run a few tests regarding the spawn interval of creatures. It seems like there is something off. For the test I killed a spawn set to 200 in the map editor. The rate_spawn in config.lua was set to 1. Here are the results:

--rate_spawn 1           = 40:40 killed spawn -> 45:41 first creature spawns -> 46:41 second creature spawns
--rate_spawn 1 test 2 = 03:40 killed spawn-> 08:40 first creature spawns -> 09:40 second creature spawns
--rate_spawn 2           = 48:40 killed spawn -> 53:42 both creatures spawn at the same time

I'm not entirely sure what causes this but I will run some more tests in the future.

**Comment by Zolias** [comment]
Further tests (all made with a rate_spawn = 1) have shown me the following:

With 70 seconds spawn time the single spawn always took exactly 180 seconds to respawn
With 110 seconds spawn time the single spawn always took exactly 180 seconds to respawn
With 125 seconds spawn time the single spawn always took exactly 240 seconds to respawn
With 60 seconds spawn time the single spawn always took exactly 120 seconds to respawn
With 10 seconds spawn time the single spawn always took exactly 20 seconds to respawn

I'm currently trying to understand spawn.cpp to figure out if the bug is created in there.

**Comment by okk3** [comment]
Hello @Zolias 

after comparing this to my working 0.4 sources, I noticed that OTHire uses the cleanup() function and I couldn't find much about it in the sources that would check for when the monster's been killed.

I would suggest you to remove the cleanup() function which in my opinion hasn't been decently implemented and try it with this code:

Please make sure to comment if you have any problems with that.

```cpp
void Spawn::checkSpawn()
{
#ifdef __DEBUG_SPAWN__
	std::cout << "[Notice] Spawn::checkSpawn " << this << std::endl;
#endif
	checkSpawnEvent = 0;

	Monster* monster;
	uint32_t spawnId;

	for(SpawnedMap::iterator it = spawnedMap.begin(); it != spawnedMap.end();)
	{
		spawnId = it->first;
		monster = it->second;

		if(monster->isRemoved())
		{
			if(spawnId != 0)
				spawnMap[spawnId].lastSpawn = OTSYS_TIME();

			monster->releaseThing2();
			spawnedMap.erase(it++);
		}
		else if(!isInSpawnZone(monster->getPosition()) && spawnId != 0)
		{
			spawnedMap.insert(SpawnedPair(0, monster));
			spawnedMap.erase(it++);
		}
		else
			++it;
	}

	uint32_t spawnCount = 0;
	for(SpawnMap::iterator it = spawnMap.begin(); it != spawnMap.end(); ++it)
	{
		spawnId = it->first;
		spawnBlock_t& sb = it->second;

		if(spawnedMap.count(spawnId) == 0)
		{
			if(OTSYS_TIME() >= sb.lastSpawn + sb.interval)
			{
				if(findPlayer(sb.pos))
				{
					sb.lastSpawn = OTSYS_TIME();
					continue;
				}

				spawnMonster(spawnId, sb.mType, sb.pos, sb.direction);
				++spawnCount;
				if(spawnCount >= (uint32_t)g_config.getNumber(ConfigManager::RATE_SPAWN))
					break;
			}
		}
	}

	if(spawnedMap.size() < spawnMap.size())
		checkSpawnEvent = Scheduler::getScheduler().addEvent(createSchedulerTask(getInterval(), boost::bind(&Spawn::checkSpawn, this)));
#ifdef __DEBUG_SPAWN__
	else
		std::cout << "[Notice] Spawn::checkSpawn stopped " << this << std::endl;
#endif
}```

**Comment by Zolias** [comment]
Thanks a lot for your suggestion! I removed the cleanup function & tried your solution but recieved some errors during comiling:

> 1>------ Build started: Project: Initium, Configuration: Release Win32 ------
1>  spawn.cpp
1>spawn.cpp(395): error C3861: 'SpawnedPair': identifier not found
1>spawn.cpp(427): error C2039: 'getScheduler' : is not a member of 'Scheduler'
1>          c:path\scheduler.h(79) : see declaration of 'Scheduler'
1>spawn.cpp(427): error C2228: left of '.addEvent' must have class/struct/union
1>          type is ''unknown-type''
1>spawn.cpp(427): error C3861: 'getScheduler': identifier not found
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by babymannen** [comment]
Your problem is that it's not a rate of the spawn time, but rather a rate of the amount of creatures. Not sure if it's even working.

**Comment by peonso** [comment]
From @babymannen comment look like this report is invalid.

**Comment by peonso** [comment]
https://github.com/otland/forgottenserver/pull/3134
