### ISSUE TITLE
Parcel

### ISSUE THREAD

**Issue by Qwizer** [TwistedScorpio/OTHire#178]
can climb on top of parcel, without needing to stack new parcels on the side.
![image](https://user-images.githubusercontent.com/9012031/34828552-b57841a8-f6bc-11e7-8ae8-a1d957aa47f3.png)
![image](https://user-images.githubusercontent.com/9012031/34828602-d095bc4a-f6bc-11e7-9b40-0d241c4abc2f.png)

**Comment by JakesFromBB** [comment]
As far as I know it's intended in 7.72

**Comment by TwistedScorpio** [comment]
This is definitely intended behavior for Tibia 7.72, this was only part of 7.4 and less.

**Comment by Qwizer** [comment]
okey, Anyone know how I can leave the same 7.4?

**Comment by Qwizer** [comment]
@TwistedScorpio okey, Anyone know how I can leave the same 7.4?

**Comment by peonso** [comment]
There is an already open issue for this https://github.com/TwistedScorpio/OTHire/issues/154
