### ISSUE TITLE
HardcorePVP and NPCs

### ISSUE THREAD

**Issue by jpgmassuco** [TwistedScorpio/OTHire#179]
I dont know what one thing makes sense with other, but IF you turn the server to hardcore pvp on config.lua, the npcs dont works.

-- options: openpvp/pvp, optionalpvp/no-pvp, hardcorepvp/pvp-enforced
worldtype = "hardcorepvp"

Just changed this to hardcorepvp and repently the npcs dont answer when you greet him,.

**Comment by JakesFromBB** [comment]
Can't reproduce. Working fine here.

**Comment by jpgmassuco** [comment]
I will check again and edit here, but Im sure that it happened. I have changed the world type for one test, and the npcs stopped work, then changed back to openpvp, and worked again. i will check.

**Comment by peonso** [comment]
@jpgmassuco any news?

**Comment by peonso** [comment]
I couldn't reproduce it, closing.
