### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by Qwizer** [TwistedScorpio/OTHire#180]
Unknown packet header: 0, player Frozen Healer
Unknown packet header: 0, player Frozen Healer

why does this error appear that prevents login

**Comment by peonso** [comment]
No idea, it's started to happen after u made some changes? It's a brand new character?

**Comment by Qwizer** [comment]
no, normal char, with old client 7.72, only some.

**Comment by peonso** [comment]
If you can't give me the steps to reproduce the error I can't work on it.

**Comment by Qwizer** [comment]
I do not know how, from time to time it appears in the logs, I have no idea what it is. I do not know how, from time to time it appears in the logs, and the player can not log in for a while.

**Comment by Anastaciaa** [comment]
That message: "Unknown packet header" doesnt exist in othire sources. So that probably your custom code.

**Comment by Anastaciaa** [comment]
That happens if you inject some kind of bots into client.
