### ISSUE TITLE
ladder BUG

### ISSUE THREAD

**Issue by Qwizer** [TwistedScorpio/OTHire#181]
If you have anything under the stairs, you can not up.

**Comment by Qwizer** [comment]
you can not up

**Comment by Qwizer** [comment]
![image](https://user-images.githubusercontent.com/9012031/35787342-12e5ead6-0a0c-11e8-9ad8-0de97c37dc31.png)

**Comment by Qwizer** [comment]
![image](https://user-images.githubusercontent.com/9012031/35788964-99c1f710-0a17-11e8-9d26-d4dc4ebba20f.png)

**Comment by okk3** [comment]
Yo @Qwizer,

are you using the current actions folder?

I couldn't reproduce the error.

Kindest Regards,
Okke

**Comment by Qwizer** [comment]
yeah, @okk3

**Comment by Qwizer** [comment]
function onUse(cid, item, frompos, item2, topos)
	newPos = {x = frompos.x, y = frompos.y, z = frompos.z}
	if (isInArray(LADDER, item.itemid) ) then
		newPos.y = newPos.y + 1
		newPos.z = newPos.z - 1
		doTeleportThing(cid, newPos)
	else
		newPos.z = newPos.z + 1
		doTeleportThing(cid, newPos)
	end
	return true
end


using tibialegacyserver

**Comment by Qwizer** [comment]
for what I saw here and problem in the items.otb, I changed some items, with itemeditor 0.2.2

**Comment by Qwizer** [comment]
![image](https://user-images.githubusercontent.com/9012031/35829447-a616ee5a-0aa1-11e8-99b0-3f51ddb7e34b.png)
othire ultimate version, linux debian 8

**Comment by Qwizer** [comment]
@TwistedScorpio @peonso @okk3 @diegorodriguesvieira

**Comment by JakesFromBB** [comment]
It's working fine here. You've messed up something by yourself. 
Try with the clean sources and datapack.

**Comment by Qwizer** [comment]
I compiled clean sources in Debian 7, and it did the same thing.

**Comment by peonso** [comment]
Seems that OP indeed fucked up. **https://otland.net/threads/ladder-bug-when-any-item-is-below.257112/page-2#post-2489781**
