### ISSUE TITLE
Palladin attack bug.

### ISSUE THREAD

**Issue by Anastaciaa** [TwistedScorpio/OTHire#186]
When palladin is on the same stack with any player or monster he is not able to shoot(hit).
Basically he is shooting but can't make hit.

Do you have this issue too?

**Comment by Anastaciaa** [comment]
Actually solved this, but i guess it's not bug because it happen on every otserver, i dont know about tibia server.

**Comment by Felipe1993** [comment]
Hello @Anastaciaa 
could you post the codes to solve this please?
thanks in advance mate

**Comment by peonso** [comment]
@Anastaciaa 
It's a bug, don't happens on real servers (realots). Please share how you solved it.

**Comment by Anastaciaa** [comment]
under this line
>https://github.com/TwistedScorpio/OTHire/blob/322095b12dbbfe6644dff6a615f43d7dcd27e2ab/source/weapons.cpp#L898

add:
>case 0: chance = (uint32_t)((float)1.2 * std::min(skill, (uint32_t)74)) + 1; break;
