### ISSUE TITLE
Ranged monsters (warlocks, hunters, etc...) strange behavior

### ISSUE THREAD

**Issue by thivod** [TwistedScorpio/OTHire#189]
Ranged monsters like Warlocks, hunters, amazons, etc... act strange when they are chased by a few opponents.

My guess is that when they are chased by some enemies and they change target they dancestep worng, moving like 2 or 3 times in one sec, like the video a just posted at the link below.

Video:

[Link - vimeo.com](https://vimeo.com/263816665)

Pay close attention to the 47th second and furthers - warlock will wrongly dancestep 2 times when being chased by the orcs warlords.

EDIT:

Maybe it can happen with other monsters as well, when they're chasing a target, e.g. if a player starts to flee from a group of 3-4 heoroes, then they might behave like the ranged monsters do, as shown at the vídeo.

**Comment by Anastaciaa** [comment]
This might happen because of disappearing ladder fixes in OTClient

**Comment by thivod** [comment]
Yea, that might be true.

I'm making some tests on standard client and will posta an update later.

Thx for the answer!


*Thiago Martins*
Advogado | TVM Advogados
(11) 95921-7045 <https://api.whatsapp.com/send?phone=5511959217045>

Cível - Empresarial - Trabalhista
Visite meu site! Clique aqui. <http://www.adv.com.br/>


2018-04-09 9:35 GMT-03:00 Anastaciaa <notifications@github.com>:

**Comment by Anastaciaa** [comment]
So I was right?

**Comment by thivod** [comment]
Yea, you're totally right!

Thanks for sharing the solution.




*Thiago Martins*
Advogado | TVM Advogados
(11) 95921-7045 <https://api.whatsapp.com/send?phone=5511959217045>

Cível - Empresarial - Trabalhista
Visite meu site! Clique aqui. <http://www.adv.com.br/>


2018-04-09 13:55 GMT-03:00 Anastaciaa <notifications@github.com>:

**Comment by thivod** [comment]
When using the standard client, it seems that the monster's dancestep is
more accurate.

Disappearing ladder fixes in OTClient seems to be the cause.


*Thiago Martins*
Advogado | TVM Advogados
(11) 95921-7045 <https://api.whatsapp.com/send?phone=5511959217045>

Cível - Empresarial - Trabalhista
Visite meu site! Clique aqui. <http://www.adv.com.br/>


2018-04-09 15:51 GMT-03:00 Thiago Martins <thi.vod@gmail.com>:

**Comment by peonso** [comment]
So it's client sided?

**Comment by thivod** [comment]
Yes it is.

On standard CipSoft client it won't occur.
I thought it was something related to the staticattack monster flag that was recently donwgradade to value 80, but it's not.
