### ISSUE TITLE
Non-Pvp

### ISSUE THREAD

**Issue by JasonRox18** [TwistedScorpio/OTHire#190]
when set to non-pvp, people are still able to attack/kill each other with skull system.
this happens when you hold ALT, and click really fast on the person.

**Comment by babymannen** [comment]
Are you using Non-PvP tilestate in any other place than rookgaard?

**Comment by JasonRox18** [comment]
I haven't touched the map In any way like that, I thought the non pvp would be hard coded into the distribution?


Get Outlook for Android<https://aka.ms/ghei36>

________________________________
