### ISSUE TITLE
Another NPC Issue regarding conversation

### ISSUE THREAD

**Issue by JasonRox18** [TwistedScorpio/OTHire#191]
when you speak to npc for quests, if they have around 5 different things to say based on one trigger word they will only say the last thing and skip the rest.

**Comment by babymannen** [comment]
Sounds like a bad scripting. Post the NPC script you're having issues with and let us have a look!

**Comment by JasonRox18** [comment]
I sort of solved this issue, I read up it was a problem with the delay script used, like it's a true or false option, so I made it spit everything out rather than pausing between

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peonso** [comment]
Actual code doesn't handle more than one reply, regardless of delay, the code should be added to handle those sort of issues.

**Comment by Felipe1993** [comment]
i want to learn.. were shouldd i start @peonso
