### ISSUE TITLE
Trade item issue.

### ISSUE THREAD

**Issue by Anastaciaa** [TwistedScorpio/OTHire#193]
If player1 trade stackable item with player2 like crystal coins and player1 put for example 44 cc on arrow slot and trade another item for example sword with trade partner player2 who giving you on 100 cc on trade for the sword then if you both accept trade, 44cc on arrow slot in player1 will fill to 100cc and rest(44cc) will stay in trade partner bp player2 what is bug because all 100cc money should be moved to player 1.

I know which function fails but i dont know what exactly causing this in this function.
This is the function. Something is wrong with autostack i suppose.
>https://github.com/TwistedScorpio/OTHire/blob/322095b12dbbfe6644dff6a615f43d7dcd27e2ab/source/player.cpp#L3088

I solved this by replacing whole function from avesta.

**Comment by peonso** [comment]
Won't it break autostack?

**Comment by peonso** [comment]
https://github.com/tarantonio/avesta/blob/master/src/player.cpp#L2652-L2723

**Comment by Anastaciaa** [comment]
It will break autostack i guess.
