### ISSUE TITLE
Stacked Parcel/Box etc Bug

### ISSUE THREAD

**Issue by JasonRox18** [TwistedScorpio/OTHire#198]
When stacking 3 parcels or boxes/anything you can stand on it allows you to climb upto a new ledge but does not allow you to come back down again. Like at darashia giant spider for instance.

**Comment by JakesFromBB** [comment]
Workin' fine here:
https://gyazo.com/9596985881141c96a0a339dc23bbfdb3

**Comment by JasonRox18** [comment]
yeah, in 7.72 you could never step ontop of 3 stacked parcels

**Comment by peonso** [comment]
@JasonRox18 actually you could, you couldn't in 7.4.
