### ISSUE TITLE
Might Ring problem

### ISSUE THREAD

**Issue by Arahnus** [TwistedScorpio/OTHire#200]
If you are carrying might right and it gets rid of your other rings stop working, you need to relog to start use them again.

**Comment by peonso** [comment]
Could you tell me the exact steps to reproduce the bug?

**Comment by Arahnus** [comment]
Dunno if it's fixed on newest release of OTHire. I am just experiencing this bug on my server which is 0.0.3 but still updating with commits. Just finish your might ring and all of the sudden any of your life/roh ring will be dead. Very troublesome on my server.
