### ISSUE TITLE
Ping error

### ISSUE THREAD

**Issue by rrodriguesrm** [TwistedScorpio/OTHire#203]
Hello, I'm trying to use OThire + OTclient, but ping is not working, the ping menu doesnt appear. I tested with TFS and its normal. Is there something that I have to change?

**Comment by Felipe1993** [comment]
In 7.x ping didnt show up....  Maybe you're talking about fps and for me works fine

**Comment by peonso** [comment]
OTHire is meant to mimic 7.72 Tibia gameplay, it's not a part of it, so it's not something that is missing. Feel free to push a commit with supporting this feature for OTClient, but it's not the project focus.
