### ISSUE TITLE
[Minor issue]Open holes on sand use wrong hole id and also wrong tool

### ISSUE THREAD

**Issue by Felipe1993** [TwistedScorpio/OTHire#204]
@peonso @okk3
PD: Srry by the delay in my answer to this

This is how othire is working now (im using original files from here not from legacy) to open a hole on sand i have to use pick and the hole id is wrong PD: I have no idea about how to change this even when i been struggling into actions/lib
[url=https://imgur.com/iAcRqHD][img]http://i.imgur.com/iAcRqHD.png[/img][/url]

This is how OTHIRE works with legacy server libs. Everything is okey but when the hole is closed i get an error in console server it doesnt happens always dunno why

with this files the hole sand id works okey but i have an exe console error at some point
here are the files:
real repo of @peonso https://github.com/peonso/tibialegacyserver
https://github.com/Felipe1993/tibialegacyserver

[img]https://i.imgur.com/0W5Ceq5.png[/img]

This is the error that appears on exe with legacy files

Lua Script Error: [Action Interface]
in a timer event called from:
data/actions/scripts/tools/shovel.lua:onUse

LuaScriptInterface::luaDoTransformItem(). Item not found

Lua Script Error: [Action Interface]
in a timer event called from:
data/actions/scripts/tools/shovel.lua:onUse

LuaScriptInterface::luaDoTransformItem(). Item not found

**Comment by Felipe1993** [comment]
I think i solved it i think i didn't change the whole libs the missing file to change was at actions/lib/actions.lua

**Comment by peonso** [comment]
This is not an error, it work as intended, you want a custom script with specific behavior, open an otland support thread and tag me.

**Comment by Felipe1993** [comment]
Okey thanks you @peonso
