### ISSUE TITLE
Othire doesnt handle bless

### ISSUE THREAD

**Issue by Felipe1993** [TwistedScorpio/OTHire#207]
As tittle says or it doesnt works players always moldes their backpacks and much exp

**Comment by Felipe1993** [comment]
Legacy npcs

**Comment by peonso** [comment]
https://pastebin.com/yBMA7kuN

**Comment by Felipe1993** [comment]
@peonso It worked man but i wonder if you could add an option to increase the paid ammount while the player gets mover levels he has to pay more

would be that possible?

**Comment by peonso** [comment]
Everything is possible, but I'm not doing nor inplementing custom code here.

**Comment by Felipe1993** [comment]
Okey thanks a Lot i'll así help at Otland it's worked atleast i was checking 8.7 SVN droploot code and it's the same at othire like SVN is pretty old i thought the code never was implement 
This Helped me a lot i was trying to implement tfs 0.4 code lol
