### ISSUE TITLE
GM Proper Functionality (as per regulated in OTs)

### ISSUE THREAD

**Issue by tornadia** [TwistedScorpio/OTHire#209]
https://github.com/TwistedScorpio/OTHire/blob/master/source/player.cpp#L841
In order to implement maximum speed on GM authorities given the PlayerFlag_SetMaxSpeed (as seen on the flag editor).

Change:
`	if(getSpeed() > PLAYER_MAX_SPEED){`
to:
`	if(getSpeed() > PLAYER_MAX_SPEED || hasFlag(PlayerFlag_SetMaxSpeed)){`

Will soon add other fixes, such as the ability to move items/creatures farther than they are designed, with no delay, and see itemids, along with other special descriptions when using onLook. This is only in order to achieve a higher playability for GM and other figures of authorities added within the server, so that OT developers can focus more on playability and game design other than hassling with GM workings.

**Comment by tornadia** [comment]
Change god flags to see item description onLook: 18689080401912

**Comment by Felipe1993** [comment]
i want this too check items id tiles id actions unique ids etc would be a good function
