### ISSUE TITLE
Speedhack

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#21]
While moving with keyboard, you keep right clicking on map to move in the same direction (never stop pressing key arrows), your character like speed hack while doing it. It's like a map click speed hack where people use the ground when they walk.

Better described here http://otland.net/threads/speed-hacking.7418/

**Comment by babymannen** [comment]
Effective way to prevent this is:

in Game::PlayerUseItem(...)

Under:

Thing* thing = internalGetThing(player, pos, stackPos, spriteId, STACKPOS_USEITEM);

add:

player->lastStepCost = 3;

**Comment by tarantonio** [comment]
This is client related, not server related, AFAIK

**Comment by gesior** [comment]
This is because **when you map click server take control over your character** [click just once, don't have to click it more, when you click more, you can think that you run faster, because of 'character animation lag' in client, but speed is same) .

It's not 'hacking' anything. It just run with 'character' speed - ignore ping, keyboard delay, Windows input delay.. everything. There is no way to run with keyboard as fast as you can with map click.

**Comment by Pietia10** [comment]
Gesior , not exactly on Cipsoft Tibia it's not the case you run at same speed when you map click and when you walk with keyboard it doesn't make any difference at all so there is a way to address this .

**Comment by Anastaciaa** [comment]
This issue is more like client side this is fixed in OTC

**Comment by gesior** [comment]
Anyone checked what packets and with what time between them server receive when you 'speed hack'? Is there any other situation when we get this kind of packets (hotkey spam or something)?
If we can't fix it, maybe we can detect that 'bad behavior' and punish (lastStep = 3) players that use this cheat?
On my medium level war server I detected somehow speed hackers and paralyze them for using this cheat, but I don't remember how it worked.. it was 5 years ago.

OTS got some schedule of actions (like make next step, onThink events and many others) and as we know 'delayed events' is not a good way to run things when miliseconds matter [checkout otservlist.org server start countdown, refresh site after minute.. JS setTimeout lost somehow few seconds! wtf?].

Maybe normal character, when you run by arrows or map click is not running full speed? Maybe it lose 5-10 ms per step? Stop movement for 5 ms, so you can't see that, but after some distance, you will see that you should run there in 1.54 sec and it takes 1.65.

If it's true, solution would be some event that trigger every milisecond and check if player can move (got queued steps).

**Comment by peonso** [comment]
Made some tests today, opened another client and saw the character moving in the other screen. It doesn't seem to speedhack at all, the character moves smoothly, making this bug probably just a visual glitch in client.

**Comment by peonso** [comment]
[![Youtube Speedhack test video.](https://i.ytimg.com/vi/KYAw2gHBP-M/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&pt=325&jpgq=85&dct_sp=100&sigh=BA38NkAp5_nJWp7DXVcl3m9WBQU)](https://youtu.be/KYAw2gHBP-M)

**Comment by tarantonio** [comment]
Maybe a look at this tip can solve the bug?
[https://otland.net/threads/fixed-right-click-speed-hack-fix-othire.253595/](url)

**Comment by Anastaciaa** [comment]
@tarantonio
your link doesnt work

**Comment by peonso** [comment]
Gonna test later. Saving this, REALLY DON'T WANNA RISK TO LOSE THIS ANYHOW.

> Add this to your playerUseItem

`if(player->eventWalk!=0){`
`player->lastStepCost=2;`
`}`

**Comment by peonso** [comment]
@tarantonio 
worked
