### ISSUE TITLE
Paralize  rune  it's too OP

### ISSUE THREAD

**Issue by Felipe1993** [TwistedScorpio/OTHire#210]
When a player got paralize and he use exura utani hur etc the get still paralized for so many secconds like 3 or 4

**Comment by peonso** [comment]
If he is in the middle of the step that what should happen, isn't it? Until the step is completed.

**Comment by Felipe1993** [comment]
exactly  if the player is walking it took too much to remove the paralize condition, the player has to stop walking to conclude the paralize condition i used to play at 7.x versions and i don't remember that it worked in that way i have a code but i haven't tested yet because it works for tfs 0.4 maybe i will give it a try and post the results here but im not sure at all if it going works
