### ISSUE TITLE
time To Decrease Frags

### ISSUE THREAD

**Issue by AninhaPaula** [TwistedScorpio/OTHire#212]
where to set the timeToDecreaseFrags??

**Comment by okk3** [comment]
Hello AninhaPaula,

this function isn't implemented on OTHire, therefore you can use frags by day, week and month.

Best wishes,
Okke

**Comment by AninhaPaula** [comment]
Is there any way I can deploy it? and very important this function in oldserver

**Comment by okk3** [comment]
There is a way, you can differ files and compare what is to be done, you can take as reference the old-tfs repository, which has this specific function you want to have.

The link for it is here: https://github.com/otland/tfs-old-svn

Best Wishes,
Okke

**Comment by peonso** [comment]
OTHire aim to replicate 7.72 Tibia. If someone want to implement this gimmiks as alternatives no problem, but it's not like it's missing something.
