### ISSUE TITLE
Diagonal Movement Glitch / fromPos glitch - OTCLIENT

### ISSUE THREAD

**Issue by cjrz74** [TwistedScorpio/OTHire#214]
https://streamable.com/yjyqu

1,3,7,9 cause weird glitch in movements when hit by monsters.

**Comment by peonso** [comment]
It seams a client problem.

**Comment by Felipe21** [comment]
indeed it's

**Comment by Wirless** [comment]
its because of checkcreature distance when attacking. it somehow takes the position of monster when you move diagonally and pushes you through it
