### ISSUE TITLE
Support/Attack spells not sharing exhaust

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#22]
Healing and attacking spells are not sharing exhaust.

From what I remember, at 7.72 era exhaust should work like that:
After an aggressive spell you should wait 2 seconds to cast any other spell.
After an non-aggressive spell you should wait 1 second to cast any other spell.
But it's working like current Tibia, http://tibia.wikia.com/wiki/Exhaust. I can, for exemple, heal myself (exura vita) + GFB at the same moment. Or exura vita, GFB a fraction of time after that, and exura vita again 1 second after the first exura vita.

**Comment by babymannen** [comment]
In spells.cpp, 

bool Spell::playerSpellCheck(Player* player) const

Scroll down and find:

if( (isAggressive && player->hasCondition(CONDITION_EXHAUST_COMBAT)) ||
    (!isAggressive && player->hasCondition(CONDITION_EXHAUST_HEAL)) )

Change to:

if (player->hasCondition(CONDITION_EXHAUST_COMBAT) || 
    player->hasCondition(CONDITION_EXHAUST_HEAL))

**Comment by tarantonio** [comment]
This fix it's not working as intended. I made this changes on engine, recompiled, and the problem remains.

**Comment by peonso** [comment]
It does work @tarantonio 

https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-54#post-2241878
