### ISSUE TITLE
Creature should walk over pitfall

### ISSUE THREAD

**Issue by Ochmar** [TwistedScorpio/OTHire#220]
https://i.imgur.com/Sn9xgFh.png
Monsters/player follow pathing should no try to avoid **pitfall** tiles like this one.
It should be possible for the creature to drop down with this tile "by accident".

**Comment by peonso** [comment]
It's something wrong with items.otb?

**Comment by Ochmar** [comment]
In my opinion, no.
The thing is that this pitfall is one "specific" item. No item in game has the same property as pitfall. I think that it's floorChangeDown() is true, but should **not** be detected by pathing, follow, auto click etc.
In my opinion, we should add to tile.cpp another flag like
TILE_STATE_FLOORCHANGE_HIDDEN
and this item should have this attribute.
This item should **not** grant` TILE_STATE_FLOORCHANGE`, neither `TILE_STATE_FLOORCHANGE_DOWN` flag from `void Tile::updateTileFlags`.

Then, in combat.cpp we should check (pseudocode)
```
if(tile->floorChange() ||  [tile is TILE_STATE_FLOORCHANGE_HIDDEN])
return RET_NOTENOUGHROOM;
```
to prevent fire fields, magic walls etc on this field.
(because it should not be "floorChange() detected by source. But it is floor change in game-sense meaning.)

This is, by far, best fix I could think of. And it has some logic behind.


I don't know, however, if that's clear so feel free to ask.

**Comment by peonso** [comment]
If you have items 102+1066 you get the desired behavior? If so maybe it's intended, so you can have a way to get both behaviors if you desire.

**Comment by Ochmar** [comment]
1066 is a wall in my repo, but both 3310 and 293 (different pitfalls in my repo) do not work properly.

**Comment by peonso** [comment]
The FLOORCHANGE could be removed from the item and it could be handled through "movements".

**Comment by Ochmar** [comment]
You're right. Totally forgot about easier implementation...
My solution is more elegant (or is it really?), but it's also much effort, while low gain.
Your solution is easier to implement, but please be careful with not only onStepIn, but also onFieldAdd (or however it's called in this distro). 

Meaning, I'd close this issue once .lua solution is implemented and no source edit is needed (but it's achievable by doing so).
