### ISSUE TITLE
CreatureScripts 'onLogout'

### ISSUE THREAD

**Issue by tornadia** [TwistedScorpio/OTHire#226]
When using onLogout scripts, the Player::canLogout method calls every script (unnecessarily) because of the [condition in line 4727](https://github.com/TwistedScorpio/OTHire/blob/master/source/player.cpp#L4727), as **long as the player is online** and **also when the player logs out**. My suggestion to fix this is pass a variable to the onLogout(cid) function so that it is onLogout(cid, canLogCheck), or alternatively, comment these lines or add another creaturescript for this purpose.

**Comment by tornadia** [comment]
#225 also refers to this, please make sure it is merged. Thanks.

**Comment by peonso** [comment]
closed by https://github.com/TwistedScorpio/OTHire/commit/0735d6783dc6822acd4075501dec824896546177
