### ISSUE TITLE
Cannot connect error 10061 

### ISSUE THREAD

**Issue by Kuhicop** [TwistedScorpio/OTHire#228]
Hello, 

I got an error only with OTHire server, with other servers I don't have any problems.

People can't connect they're getting error 10061, but I can connect from any internal address.

I just made git clone --recursive othirerep to clone the git.

Then compiled in vs express 2010 as the wiki says, 0 errors, everything ok.

People is trying to connect with default RSA + OTClient | Tibia client

But I also tested changing the RSA from server and client and didn't work.

Of course I have ports open 80, 443, 3306, 7171, 7172 and config.lua is pointing to my global/public IP address.

Any ideas?

**Comment by Wirless** [comment]
what do you need 3306 open for? it is very insecure to open your database to public even if it is limited to your ip address

**Comment by Kuhicop** [comment]
remote administration tools I've coded, but It was my fault I wasn't using SSH for it
