### ISSUE TITLE
Errors compiling with docker-compose

### ISSUE THREAD

**Issue by giigaby** [TwistedScorpio/OTHire#229]
Hello,

The first problem i had with docker-compse build it was because it had a problem in the Dockerfile so i had to add a 2n RUN.

![imagen](https://user-images.githubusercontent.com/49292595/58721531-75d9ee00-83d5-11e9-839b-86af3c5f179e.png)

When is it compiling there a some errors in some files not sure if its normal.
In the end make just fails don't know why
![imagen](https://user-images.githubusercontent.com/49292595/58722394-9c008d80-83d7-11e9-95e4-3faa8daabf12.png)

My Docker version 18.06.1-ce, build e68fc7a and i am using ubuntu 18.04

**Comment by tgorskievo** [comment]
@peonso have the same issue, could you double check?
