### ISSUE TITLE
Monster outfit spell

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#23]
I can't get this to work.

`<attack name="outfit" interval="1000" chance="17" range="7" monster="rabbit" duration="20000"/>`

But this two do work.

`<attack name="outfit" interval="1000" chance="9" range="7" item="3976" duration="4000"/>
<defense name="outfit" interval="1000" chance="1" monster="bat" duration="6000"/>`

**Comment by JakesFromBB** [comment]
I've tried this and works fine:

<attack name="outfit" interval="2000" chance="14" range="7" monster="rabbit" duration="20000">
			<attribute key="areaEffect" value="blueshimmer"/>
		</attack>
