### ISSUE TITLE
Cannot connect to a login server

### ISSUE THREAD

**Issue by Relyxia** [TwistedScorpio/OTHire#230]
I'm trying to connect to my server and getting this error
![imagen](https://user-images.githubusercontent.com/51744529/59465661-adac5100-8e2b-11e9-8ece-870c2aa2feb9.png)

I can login with other engines but not with this one.
Didn't change RSA or anything I'm using otservlist Tibia Loader with 7.7 client
![imagen](https://user-images.githubusercontent.com/51744529/59465748-df251c80-8e2b-11e9-9668-a6ea28d33428.png)

My client is pointing to the right address
![imagen](https://user-images.githubusercontent.com/51744529/59465865-2a3f2f80-8e2c-11e9-9e42-d5912a20f755.png)

Any idea?
Thanks!

**Comment by JakesFromBB** [comment]
It's for 7.72. Not 7.7.

**Comment by Relyxia** [comment]
I'm stunned today, was using a modified rsa client
when running from otclient i get all screen black :S
![image](https://user-images.githubusercontent.com/51744529/59471080-4518a080-8e3a-11e9-931e-8eadeb7468d2.png)

**Comment by JakesFromBB** [comment]
Just use non modified OTC. Probably something is messed up.

**Comment by peonso** [comment]
You probably have a custom client that has custom stuff that won't match with random given engine. For support try OtLand forums, you should give more information regarding your files and modifications done, screenshot you post on the other repository had an Arbalest. Also remember that you won't be able to match random client with random server with random datapack without knowing what you are doing and proper modifications.
