### ISSUE TITLE
Problema de conexão

### ISSUE THREAD

**Issue by MatheusAlbane** [TwistedScorpio/OTHire#233]
Colocando meu IPV4 no config lua as portas 7171/7172 ficam abertas, o player entra até na tela de login, seleciona o personagem mas não consegue entrar no jogo.
Se eu coloco meu ip externo no config.lua imediatamente ambas as portas se fecham. Já aconteceu algo do tipo com vocês? Como corrigiram?

**Comment by peonso** [comment]
Seção de suporte da OtLand.
