### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#235]
Fix details on death penalty formulas.

Copy Nostalrius shield formulas.

Try to reach someone from Septera to grab how throwing ranged items/spells works, regarding angles and corners.

**Comment by thivod** [comment]
Msg me and count on me, if u need help with anything.

**Comment by peonso** [comment]
https://github.com/otland/forgottenserver/pull/3223

**Comment by peonso** [comment]
Dismembered #238, #239 and #240
