### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by EnzzoCaaue** [TwistedScorpio/OTHire#26]
Im using Ubuntu 14.1 and could not compile the sourc  :|

**Comment by mykonwest** [comment]
Maybe posting more info could help us to understand the problem. Could you post the content of "/home/enzo/OTHire" and /home/enzo/OTHire/build" folders? (ls or ll would do)

**Comment by diegorodriguesvieira** [comment]
**Execuce these commands:**
``sudo apt-get install autoconf build-essential pkg-config libboost-all-dev libgmp3-dev libxml2-dev liblua5.1-0-dev libmysqlclient-dev libcrypto++-dev ccache libssl-dev lua5.1``
``cd source``
``sudo sh autogen.sh``
``sudo ./configure --enable-mysql --enable-server-diag``
``sudo make``
