### ISSUE TITLE
monster walking

### ISSUE THREAD

**Issue by dadasko2** [TwistedScorpio/OTHire#27]
Monsters won't push items like pots,drawers, monsters wont push any items with blocksolid
isn't checking if they are moveable?

**Comment by Pietia10** [comment]
Up this seems to create a problem when monster can't push blocksolid.
Monster simply can't reach you when there is for example create on his path.

**Comment by OskarD** [comment]
@TwistedScorpio why no pull request and merge?

**Comment by tarantonio** [comment]
I can't reproduce the bug, as you see in my picture larvas are coming to me to attack me advancing in diagonal between pot and stone.
In your video larvas stop at the same situation...

**Comment by peonso** [comment]
#43
