### ISSUE TITLE
Otbm loader failed to load item(items with count 0)

### ISSUE THREAD

**Issue by Pietia10** [TwistedScorpio/OTHire#30]
Hey I got following error:
FATAL: [OTBM loader] [x:32187, y:31618, z:7] Failed to load item 2666.

seems like server is not handling stackable items with count = 0 .

**Comment by babymannen** [comment]
Have you done this to your mapeditor?

https://github.com/TwistedScorpio/OTHire/wiki/How-to-use-RME-for-this-OTServer

**Comment by Pietia10** [comment]
Wow it worked thanks ;-)

**Comment by Pietia10** [comment]
Well map loading part was done but there is a crash after loading of map generating minidump .
