### ISSUE TITLE
Some spawns doesn't spawn

### ISSUE THREAD

**Issue by Pietia10** [TwistedScorpio/OTHire#32]
Some spawns doesn't spawn (I checked spawn time it's 150 and there is also spawnsize set)for example at poi dl's is there any known problem for that perhaps fire fields I deleted them tho same issue . ;X
im sure there was nobody blocking the spawn.

**Comment by TwistedScorpio** [comment]
Did you followed up this on OTLand ?

**Comment by Pietia10** [comment]
ok so the fix was to set spawn_rate to higher value or post more spawns. -- not a bug.
