### ISSUE TITLE
Readables

### ISSUE THREAD

**Issue by Watchdog87** [TwistedScorpio/OTHire#34]
When I click on a readable item, like spellbook for example, no module window with text pops up.

**Comment by EPuncker** [comment]
it is working just fine here

![2015-03-31 19_24_31-](https://cloud.githubusercontent.com/assets/4684880/6930661/a61dc1ea-d7db-11e4-9e15-fac79b48e03c.png)

**Comment by Watchdog87** [comment]
I noticed the problem lies with OT client.
