### ISSUE TITLE
Wrong decay hole

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#37]
i'm not with othire forked here, so I can't submit the fix

but https://github.com/TwistedScorpio/OTHire/blob/master/data/items/items.xml#L233 is wrong

     <item id="489" article="a" name="hole">
		<attribute key="floorchange" value="down"/>
		<attribute key="decayTo" value="9059"/>
		<attribute key="duration" value="30"/>
    </item>

Should decay to id `481` I believe.

**Comment by TwistedScorpio** [comment]
Pull request pls?
