### ISSUE TITLE
Spellbook

### ISSUE THREAD

**Issue by Emky** [TwistedScorpio/OTHire#40]
When right clicking on spellbook(id: 2175) the tibia client crashes

**Comment by Emky** [comment]
I sorted it, was missing msg->AddString(""); in protocolgame.cpp

**Comment by kombajnik** [comment]
Could you explain more how you fix this?

**Comment by kombajnik** [comment]
Becaues in protocolgame.cpp i have

if(msg){
		TRACK_MESSAGE(msg);
		msg->AddByte(0x96);
		msg->AddU32(windowTextId);
		msg->AddItemId(item);
		if(canWrite){
			msg->AddU16(maxlen);
			msg->AddString(item->getText());
		}
		else{
			msg->AddU16(item->getText().size());
			msg->AddString(item->getText());
		}

		const std::string& writer = item->getWriter();
		if(writer.size()){
			msg->AddString(writer);
		}
		else{
			msg->AddString("");
		}
	}

**Comment by tarantonio** [comment]
This issue can be closed
