### ISSUE TITLE
Stackables and cap

### ISSUE THREAD

**Issue by bangbus** [TwistedScorpio/OTHire#41]
Oi!

There's a problem with stackables and updating the cap accordingly, buying meat for example will not update the cap correctly, it might say you have 300 cap left but in reality you only have 30.

You have to drop it and pick it up again for the correct cap

**Comment by tarantonio** [comment]
I can't reproduce this issue. It's working as intended here.

**Comment by TwistedScorpio** [comment]
Can someone else try to reproduce this one bug ?

**Comment by peonso** [comment]
I can't reproduce it, tried picking stuff from ground, trade item, and buying from npc.
