### ISSUE TITLE
Guild::broadcastMessage - crash fix

### ISSUE THREAD

**Issue by gesior** [TwistedScorpio/OTHire#42]
If you use 'ProtocolGame::sendToChannel' with NULL creature, it will crash a server ('anonymous talk' - like 'Xxx killed Yyy' on 'Guild Channel' etc.).
**Reason:**
https://github.com/TwistedScorpio/OTHire/blob/master/source/protocolgame.cpp#L2298

    msg->AddString(creature->getName());

**Code try to load creature name, but that creature is NULL!**
FIX:

    if(creature)
      msg->AddString(creature->getName());
    else
      msg->AddString(""); // anonymous = no name

It fix problem with:
https://github.com/TwistedScorpio/OTHire/blob/master/source/guild.cpp#L98

    void Guild::broadcastMessage(SpeakClasses type, const std::string& msg) const

server crash.

**Comment by Emky** [comment]
do i replace the gamemaster string or place it within the 
if (type != SPEAK_RVR_ANSWER){ } ?

**Comment by gesior** [comment]
Replace:

    msg->AddString(creature->getName());

With:

    if(creature)
      msg->AddString(creature->getName());
    else
      msg->AddString(""); // anonymous = no name
