### ISSUE TITLE
Monster pathfind issue

### ISSUE THREAD

**Issue by Emky** [TwistedScorpio/OTHire#43]
Here is an issue that i came across
http://imgur.com/lf80tNH
- Monsters get stuck at objects such as parcels etc and won't go around them when chasing target. 

Would appreciate if anyone could take their time and fix since i'm not able to

**Comment by peonso** [comment]
UH trap is not intended to be present, but adding it and allowing to enable/disable the feature trough config.lua would be good.

**Comment by TwistedScorpio** [comment]
Concerning the first one issue. https://github.com/TwistedScorpio/OTHire/issues/27

**Comment by Emky** [comment]
already had that code from #27 when i wrote this issue, they still acting weird, for example a rotworm can get stuck near a parcel and won't go around it to chase you

**Comment by Emky** [comment]
i uploaded a video as an example 
https://www.youtube.com/watch?v=ds0A6LthjIA

**Comment by tarantonio** [comment]
![larva](https://cloud.githubusercontent.com/assets/7066891/13815082/74bee968-eb89-11e5-834a-9a47459e7332.jpg)
I can't reproduce the bug, as you see in my picture larvas are coming to me to attack me advancing in diagonal between pot and stone.
In your video larvas stop at the same situation...

**Comment by Emky** [comment]
thank you for letting me know, I tested again now without my changes and it works as you said it would,  I'm going trough everything now to see what misstake that i made.

**Comment by tarantonio** [comment]
this issue can be closed

**Comment by peonso** [comment]
Applied code from #27 https://github.com/TwistedScorpio/OTHire/commit/0ebb12ea5ac97b707120d5c6bc3ba502727a4b0a and this bug started to happen. Seems the work around actually added a bug.

**Comment by Seliro** [comment]
I just compiled with the latest changes and this is how it looks like for me atm:
Trapped a behemoth with barrels and it pushes them away, so that seems to be working, however i got the same result as on that image  (http://imgur.com/lf80tNH)

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/commit/0ebb12ea5ac97b707120d5c6bc3ba502727a4b0a fixed monsters with <flag canpushitems="1"/>, and bugged the ones with it set as `0`. Gonna leave as is now until a final solution comes out.

**Comment by peonso** [comment]
https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-53#post-2241718
