### ISSUE TITLE
Mute system

### ISSUE THREAD

**Issue by LuisPro** [TwistedScorpio/OTHire#45]
When i compile 0.0.2 version spam mute system not working.
On default otserv.exe (0.0.1) file all works well.

**Comment by LuisPro** [comment]
guys, can i hear ur feedback? its working on your compiled exe?

**Comment by guilhrmew** [comment]
"Mute system was not working becouse i change in config.lua "kills_to_ban = 20" to "kills_to_ban = 99999999" as a feature of war server... SICK!
I set back kills_to_ban to 20 and removed ban code from source, and mute system is WORKING!"

That is a guy who said that in this page:
https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-73

**Comment by LuisPro** [comment]
thats me sherlock xD

**Comment by guilhrmew** [comment]
LOL xD

**Comment by diegorodriguesvieira** [comment]
This bug was valid!
Fix #76

**Comment by LuisPro** [comment]
https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-73#post-2363669
just in case
