### ISSUE TITLE
Monsters cast beams and waves through wall

### ISSUE THREAD

**Issue by LuisPro** [TwistedScorpio/OTHire#53]
If monster stay 1 sqm from wall and monster cast beam or wave, everything is right, here screen:
http://i.imgur.com/lWD6Mqg.png

But when monster is in front to wall (anything, any BLOCKSOLID wall, included magic wall) and he is blocked by player, monster cast beam and wave through wall!
http://i.imgur.com/leLPiCw.png

And when monster is full traped for example by walls or magic walls (also in front to any wall) and have no blocker, monster are not cast spells through wall.

**Comment by tarantonio** [comment]
Same here
![sin titulo](https://cloud.githubusercontent.com/assets/7066891/13815565/5f21ea18-eb8b-11e5-836b-9c9e5a950e75.jpg)

**Comment by LuisPro** [comment]
yes it is a bug! becouse wall got "blockprojectile" attribute

http://i.imgur.com/i5GLVuF.png

**Comment by tarantonio** [comment]
That's not the wall we are talking about

**Comment by LuisPro** [comment]
I talk about that wall. Look my 1st screenshot.
