### ISSUE TITLE
"Are you dead"

### ISSUE THREAD

**Issue by adiif1** [TwistedScorpio/OTHire#54]
Welcome, such as the topic I have a pretty strange problem, so (the server console, or the original client / otclient there is no error log) server already compile on Linux and run it in compiled from github
describe the situation

for example, when the character dies in pvp or monster slaughtered should pop up a window "are you dead" Unfortunately for me this is not happening, figure lying on the ground and just enough alone hand I log out and choose a character again, whether it is possible to repair? whether it is the fault of lack of function in the source and perhaps lacking a script in a folder date?

**Comment by TwistedScorpio** [comment]
That is how it works under Tibia 7.7, the feature you're asking is only within modern Tibia clients, I'd say past 8.60 maybe ?
