### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by adiif1** [TwistedScorpio/OTHire#55]
:: Loading MoveEvents ...Warning: [Event::loadScript] Can not load script. ./data/movements/scripts/guilcera/hota.lua
cannot open ./data/movements/scripts/guilcera/hota.lua: No such file or directory
Warning: [Event::loadScript] Can not load script. ./data/movements/scripts/guilcera/parchment.lua
cannot open ./data/movements/scripts/guilcera/parchment.lua: No such file or directory
Warning: [Event::loadScript] Can not load script. ./data/movements/scripts/citizen.lua
cannot open ./data/movements/scripts/citizen.lua: No such file or directory

**Comment by peonso** [comment]
Those errors are my fault from my commit long ago, added some lines from my custom map to 'movements.xml', just remove the lines related to that no existant lua files.
