### ISSUE TITLE
Neither "banking" function wont update players balance

### ISSUE THREAD

**Issue by bangbus** [TwistedScorpio/OTHire#61]
I'm a novice, but shouldn't these update the players balance? And, should they even be here? I remember there was no "banking" in 7.6, you could only change your coins. Was there in 7.72?

You find these in player.cpp.

Take "withdrawMoney" for example:

    bool Player::withdrawMoney(uint32_t amount)
    {
	    if (balance < amount) {
		    return false;
	    }

	    bool ret = g_game.addMoney(this, amount);
	    if (ret) {
		    balance -= amount;
	    }
	    return ret;
    }

the luafunction:

    int LuaScriptInterface::luaDoPlayerWithdrawMoney(lua_State *L)
    {
	//doPlayerWithdrawMoney(cid, money)
	uint32_t money = popNumber(L);
	uint32_t cid = popNumber(L);

	ScriptEnviroment* env = getScriptEnv();

	Player* player = env->getPlayerByUID(cid);
	if (player) {
		if (player->withdrawMoney(money)) {
			lua_pushboolean(L, true);
		} else {
			lua_pushboolean(L, false);
		}
	} else {
		reportErrorFunc(getErrorDesc(LUA_ERROR_PLAYER_NOT_FOUND));
		lua_pushboolean(L, false);
	}
	return 1;
    }

This works great except it wont update their balance.

It lacks a `setBalance` function.

**Comment by peonso** [comment]
Can you test this npcs to see if it is working with them? 

https://github.com/peonso/tibialegacyserver/tree/master/server/data/npc

You can remove the bank function just by not using it, an setting `use_balance_house_paying = true` to false in config.lua.

**Comment by peonso** [comment]
@bangbus 
https://github.com/TwistedScorpio/OTHire/blob/8e567570eec5a2d4570a376bb7431ee280d36513/source/luascript.cpp#L1485-L1492
https://github.com/TwistedScorpio/OTHire/blob/8e567570eec5a2d4570a376bb7431ee280d36513/source/luascript.cpp#L1289

**Comment by peonso** [comment]
Just tested here, it's working.
