### ISSUE TITLE
If you exit client, it takes over a minute before it kicks the character

### ISSUE THREAD

**Issue by bangbus** [TwistedScorpio/OTHire#67]
Maybe I'm wrong but shouldn't you be logged out/kicked within seconds IF you don't have PZ block? I havent played real tibia in years so I'm not sure. Even if not, can this be changed?

**Comment by TwistedScorpio** [comment]
This happens in TFS 1.1 and 1.2 as well.

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/blob/7fd3f37293752f60109b8cad3317c13bf8d86485/source/player.cpp#L1967

**Comment by peonso** [comment]
I added the code above and it worked, I don't know if it can backlash though, gonna commit it anyway.
