### ISSUE TITLE
Invisible bug

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/OTHire#78]
I found a bug.

You become invisible as a GM.
Someone stays in the same tile as you.
You become visible.

The other user change their outfit to yours like this:
![2016-09-14 10_23_30-otclient](https://cloud.githubusercontent.com/assets/7066891/18507147/5e356cb0-7a6f-11e6-9a62-9d647469551e.png)

In this shot on the left the GM become invisible again and the user is in the same tile as GM
In the right shot you can see the bug, Tarantonio is using a GM outfit and the same name as the GM

I'm using OTCLient.

With the normal Tibia client it's worse, if you do the same, you can't do nothing once you reproduce the bug:
![2016-09-14 10_30_51-tibia](https://cloud.githubusercontent.com/assets/7066891/18507151/6397e070-7a6f-11e6-9561-5c36b43f8510.png)

It changes the oufits and names, but in the user side you are like paralyzed and can't move.
The GM can move but it becomes crazy, you move all two characters.

With two tibia clients, it's crazy:
![2016-09-14 10_35_23-tibia](https://cloud.githubusercontent.com/assets/7066891/18507156/6797181c-7a6f-11e6-96bb-6cba6073a2c7.png)

The only solution for user is to relogin.

**Comment by peonso** [comment]
It can be fixed by changing floor also. It was happening to me with characters that had `save` set to 0 and were forced to spawn in the same tile, once I logged with 2 at the same time, they spawn in the same tile and the one that logged first bugged the same way  you described here. It happened to me with a GM and a normal character also, without using the invisible command, and the bugged character was actually the gamemaster, I don't remember how I made it happen though.

**Comment by tarantonio** [comment]
It's not invisible related I think.

**Comment by babymannen** [comment]
In function: void Tile::internalAddThing(uint32_t, Thing* thing)

Change:
creatures->insert(creatures->begin(), creature);

to 
creatures->insert(creatures->end(), creature);

Credits: Ferrus

**Comment by diegorodriguesvieira** [comment]
Then I'll try and make a pull request...thanks a lot @babymannen and Ferrus

**Comment by peonso** [comment]
Too late!!

**Comment by diegorodriguesvieira** [comment]
😞

**Comment by peonso** [comment]
Try this and reverting back https://github.com/TwistedScorpio/OTHire/commit/ea43dec790f4b268b18356cf0ad187ca694d04b4
