### ISSUE TITLE
Remove drop corpse delay

### ISSUE THREAD

**Issue by diegorodriguesvieira** [TwistedScorpio/OTHire#87]
Remove from void Game::checkCreatures()

**Comment by peonso** [comment]
After creature die, corpse isn't created instantly, onThink is responsable https://github.com/TwistedScorpio/OTHire/blob/master/source/creature.h#L127

**Comment by peonso** [comment]
@diegorodriguesvieira share your workaround, please.

**Comment by diegorodriguesvieira** [comment]
Below this line add:
https://github.com/TwistedScorpio/OTHire/blob/master/source/game.cpp#L4053

```c++!
if(damage >= target->getHealth()){
  if(target->getMonster()){
    target->onDie();
  }
}
```

**Comment by peonso** [comment]
Fix applied in https://github.com/TwistedScorpio/OTHire/commit/6953b13b42d9d52b32f2f28254901106b8964087, generated this crash https://github.com/TwistedScorpio/OTHire/issues/112 and was reverted in #.

**Comment by diegorodriguesvieira** [comment]
@peonso , I believe you can close this issue...removing this delay is not safe...all servers have this delay. This is for the security of OTServ, imagine 1,000 players killing 10 monsters each at the same time?
