### ISSUE TITLE
Add party share exp

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#91]
Add necessary source modifications and talkactions scripts.

@diegorodriguesvieira

**Comment by diegorodriguesvieira** [comment]
Thanks https://github.com/brewsterl/RealOTX-7.72/blob/master/sources/luascript.cpp#L2306 for lua functions xD

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/commit/0aba7d733693999e9018661591806305cbbedb4f
