### ISSUE TITLE
Change items.otb to real 7.6

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#92]
Current items.otb is 7.92 and only works with otitemeditor 0.3.0 and some proprieties can't be edited.

@diegorodriguesvieira

**Comment by diegorodriguesvieira** [comment]
My current solution:
* Covert items.otb to version 1 with otitemeditor 0.0.2
* Paste the items.otb and items.xml from server in RME data folder
* Change https://github.com/TwistedScorpio/OTHire/blob/master/source/items.cpp#L231 to != 1

**Comment by Seliro** [comment]
i need to edit speed in items.otb, but it wont save

**Comment by diegorodriguesvieira** [comment]
I will test it

**Comment by peonso** [comment]
@Seliro I changed ground speed and tile start to bug (probably because I didn't edit dat file), but it was actually changed. [otitemeditor-0.2.2](http://www.4shared.com/zip/jFtWifSjce/otitemeditor-022.html) for both editing and downgrading current items.otb. The save buttom on the editor does nothing, you need to go through `File->Save as...`. Any downside by doing this, @diegorodriguesvieira? I have being able to use map with major version 1 instead of 2 also. Thinking about applying 

    	if (Items::dwMajorVersion != 1 && Items::dwMajorVersion != 2) {

to https://github.com/TwistedScorpio/OTHire/blob/master/source/items.cpp#L231, and changing items.otb file for the downgraded version.

**Comment by Seliro** [comment]
when i tested i used save as and aswell save button, neither worked ;p

also i had the speed value already in the dat file since i used an existing "cid"

**Comment by peonso** [comment]
@Seliro, so you fixed it?

I did a lot of tests, no problems seems to appear by allowing the server to load OTB MajorVersion 1 also,  it also loads maps done with RME default files, so I'm removing custom files from here https://github.com/TwistedScorpio/OTHire/wiki/How-to-use-RME-for-this-OTServer and allowing server to load both Major Versions 1 & 2 of otb files, people can still use old 7.92 items.otb without problem, but default one will be 7.6 Major Version 1, and I will add download like at wiki here https://github.com/TwistedScorpio/OTHire/wiki/Using-itemeditor and 7.6 items.otb converting current one with otitemeditor-0.2.2.

**Comment by Seliro** [comment]
@peonso yeah, im using item editor 0.2.2, all i needed to make it save the speed was to put it into a category for example 'ground' instead of 'other', only tested using an existing cid on the item so far tho
