### ISSUE TITLE
Party shared exp multiple numbers showing

### ISSUE THREAD

**Issue by peonso** [TwistedScorpio/OTHire#97]
The way it's calculated now after a monster die each party member wil get a white experience number above head for each party member that deals damage. Newer Tibia client/Otclient consolidate numbers and don't have to deal with it (I'm not sure though).

**Comment by peonso** [comment]
Also check if https://github.com/TwistedScorpio/OTHire/blob/322095b12dbbfe6644dff6a615f43d7dcd27e2ab/source/party.cpp#L404 shouldn't actually be ouble xpgained = experience / (memberList.size() + 1) + experience * (member_factor / 100.);

**Comment by peonso** [comment]
It's an issue on forgottenserver also? https://github.com/otland/forgottenserver/issues/629#issuecomment-37584959 I'm not sure.

**Comment by diegorodriguesvieira** [comment]
https://github.com/opentibia/server/blob/master/src/party.cpp#L406

**Comment by peonso** [comment]
Since there is a ceil and exp_stages is applied later, there are some strangers bonus, specially at lower exp monsters (20% bonus at a cave rat at 30x stage multiplier), but it's working as intended, and fixing it would require to be applying exp_stages before any round is done. So if ever it's considered an issue, it's an issue with exp_stages, because it's applied after the rounding.

I just confirmed the original bug of multiple experience messages is present in TFS 1.x also. https://github.com/otland/forgottenserver/pull/1344#issuecomment-126942861
