### ISSUE TITLE
Shared experience minor bugs

### ISSUE THREAD

**Issue by tarantonio** [TwistedScorpio/OTHire#99]
Based on my tests:
![2016-09-26 17_12_13-all](https://cloud.githubusercontent.com/assets/7066891/18839935/206ad6ac-840d-11e6-8dfc-fba671f5d7be.png)

In the screenshot you can see at least 2 minor bugs:

- [ ] You can not use shared experience. If I use !canshare talkaction always show this message, but I CAN activate and use shared experience as shown on the picture
![2016-09-26 17_27_12-otclient](https://cloud.githubusercontent.com/assets/7066891/18840399/c2f2c438-840e-11e6-9b2d-169f51859271.png)

- [ ] Shared Experience has been activated, but some members of your party are inactive. Always shows the same message when I activate !share talkaction. I'm doing something wrong?

**Comment by diegorodriguesvieira** [comment]
1- The command ```!canshare``` is used to check if the player is fulfilling all the requirements to receive the shared experience. If using this command you receive the message **"You can not use shared experience."** When the leader activate shared experience with ```!share```, the message **"Shared Experience Has Been activated, but some members of your party are inactive."** will appears.

**2- You are not fulfilling all requirements:**

- You need to heal life points of your partner, remember that your partner is with the full life will not work, or you can also attack a monster...

**Comment by peonso** [comment]
There are no bug, the timming is misleading. When you active exp share party leader is out of fight, and nearby never wouldn't be meeting requirements, making "but some members of your party are inactive" nearby an standard. Same for `!canshare`, if you try `!canshare` while hitting the monster it will say you can share experience. Gonna remove the "but some members of your party are inactive" statement, as it just confuses people (happened in Tibianic/Medivia when I played there), and change `!canshare` statement to make it more clear.
